### PR TITLE
chore(deps): update rhdh theme package

### PR DESCRIPTION
**Pull request by jerolimov**
## Description

The theme is now (with rhdh-theme 0.1.x) much more customizable. Before we provided 4 options, but now the user can customize many MUI and RHDH parameters.

Before:

https://github.com/user-attachments/assets/b3383633-a52f-4ce6-8241-2a46f1e1e327

With this PR (shows just a small subset of customization parameters):

https://github.com/user-attachments/assets/a0b3e3fe-4374-4886-ad52-074e4ad53bc9

## Which issue(s) does this PR fix

- Epic: [RHIDP-2358](https://issues.redhat.com/browse/RHIDP-2358) RHDH Theme customization and improvements for 1.2.2
- update incl. Story [RHIDP-2545](https://issues.redhat.com/browse/RHIDP-2545) [UI] Enable complete theme customization
- update incl. Story [RHIDP-2943](https://issues.redhat.com/browse/RHIDP-2943) [UI] Allow customers to configure also essential MUI theme options (font, colors)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

1. Test RHDH without theme configuration
2. Test the old theme customization options (they should still work)
3. Test a theme configuration like this:

```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  branding:
    theme:
      light:
        primaryColor: '#ff0000'
        headerColor1: '#00ff00'
        headerColor2: '#0000ff'
        navigationIndicatorColor: '#ffff00' # yellow
      dark:
      #   primaryColor: '#ff0000'
      #   navigationIndicatorColor: '#ffff00'
        palette:
          primary:
            main: '#ff00ff' # magenta
          secondary:
            main: '#00ffff' # cyan
      #     linkHover: '#ff0000'
          error:
            main: '#0000ff'
          rhdh:
            general:
              tableTitleColor: '#ff0000'
        #fontFamily: 'Comic Sans MS'    # DOESN'T WORK????
        # typography:
        #   h1:
        #     fontFamily: 'Comic Sans MS'
        #     fontSize: 136
        #     fontWeight: 400
        #     marginBottom: 10
        #   h2:
        #     fontFamily: 'Comic Sans MS'
        #     fontSize: 128
        #     fontWeight: 400
        #     marginBottom: 8
        #   h3:
        #     fontFamily: 'Comic Sans MS'
        #     fontSize: 124
        #     fontWeight: 400
        #     marginBottom: 6
        options:
          # components: backstage # rhdh or backstage
          # buttons: patternfly   # patternfly or mui
          # tabs: patternfly      # patternfly or mui
          # tables: mui    # patternfly or mui
          # ... document all options
        pageTheme:
          default:
            backgroundColor: ['#00ff00', '#00ffff']
            fontColor: '#000000'     # DOESN'T WORK????
            shape: wave
          apis:
            backgroundColor: '#ff0000'
            fontColor: '#000000'     # DOESN'T WORK????
            shape: wave
```

### CODE REVIEW

**Comment by jerolimov** [comment]
@debsmita1 @nickboldt I've also tested the quay image and updated my local installation with the helm chart.

### 1.2-105 (just to see the difference)

1 2-105-a

1 2-105-b

### next-89f3230 tag from 12 hours ago

image

image

image

image

### quay.io/janus-idp/backstage-showcase:pr-1418

pr-1418-a

pr-1418-b

### with additional customization

```yaml
upstream:
  backstage:
    appConfig:
      app:
        baseUrl: 'https://{{- include "janus-idp.hostname" . }}'
        branding:
          theme:
            dark:
              pageTheme:
                apis:
                  backgroundColor: '#ff0000'
                  fontColor: '#000000'
                  shape: wave
                default:
                  backgroundColor:
                    - '#00ff00'
                    - '#00ffff'
                  fontColor: '#000000'
                  shape: wave
              palette:
                error:
                  main: '#0000ff'
                primary:
                  main: '#ff00ff'
                rhdh:
                  general:
                    tableTitleColor: '#ff0000'
                secondary:
                  main: '#00ffff'
            light:
              headerColor1: '#00ff00'
              headerColor2: '#0000ff'
              navigationIndicatorColor: '#ffff00'
              primaryColor: '#ff0000'
```

image

image

image

**Comment by debsmita1** [comment]
verified the changes 
/lgtm

**Pull request merged**
