### PR TITLE
test(e2e): cut on some timeouts

### PR DESCRIPTION
**Pull request by nilgaar**
## Description

It is clear that test job can get quite demanded sometimes. Cutting the timeouts shall help the tests to run (and fail) faster.

## Which issue(s) does this PR fix

sorry there is no ticket for this, is just general tipy up

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by gashcrumb — APPROVED** [review]

**Review by christoph-jerolimov — APPROVED** [review]
This is the right direction 👍

/lgtm

**Review by josephca — APPROVED** [review]
/lgtm

**Pull request merged**
