### PR TITLE
chore(deps): bump quay plugin to 1.5.10

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Description

Bumping quay plugin version to include the following fix
- Add new queued status for the images that are queued for vulnerability scan - https://github.com/janus-idp/backstage-plugins/pull/1400 
## Which issue(s) does this PR fix

- Fixes #?

https://issues.redhat.com/browse/RHTAPBUGS-1184

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
@nickboldt can we get this in 1.1.x ? 
 
 cc: @jrichter1

**Comment by nickboldt** [comment]
@lsharar needs approval from RHTAP & RHDH PgM, as the scope of 1.1.1 continues to creep...

**Comment by nickboldt** [comment]
Decision on PgM call: OK for main, rejected for 1.1.1.

**Comment by karthikjeeyar** [comment]
@nickboldt It seems like quay plugin is already updated as part of this PR https://github.com/janus-idp/backstage-showcase/pull/1140

**Comment by nickboldt** [comment]
> It seems like quay plugin is already updated as part of this PR #1140

yep, it's :chaos: around here. :D

**Pull request closed without merging**
