### PR TITLE
feat(rbac): update rbac plugin to 1.33.2

### PR DESCRIPTION
**Pull request by divyanshiGupta**
## Description

Update rbac frontend to include the following

https://github.com/backstage/community-plugins/pull/1985
https://github.com/backstage/community-plugins/pull/2061
https://github.com/backstage/community-plugins/pull/2067

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-5063

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]

**Comment by christoph-jerolimov** [comment]
I stopped the re-test to have CI bandwidth for PRs that try to solve the CI issues. Please wait with retests until we have a heartbeat again. Thanks for your patience.

/hold

**Pull request closed without merging**
