### PR TITLE
chore(deps): bump 3scale plugin

### PR DESCRIPTION
**Pull request by PatAKnight**
## Description

Updates the 3scale backend plugin

## Which issue(s) does this PR fix

- Fixes [RHIDP-2903](https://issues.redhat.com/browse/RHIDP-2903)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

@AndrienkoAleksandr are you able to test this to make sure that it works as expected?

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
I see error in the RHDH logs:

```
{"level":"error","message":"dynamic backend plugin 'backstage-community-plugin-3scale-backend-dynamic' could not be loaded from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-community-plugin-3scale-backend-dynamic-3.0.0': the module should either export a 'BackendFeature' or 'BackendFeatureFactory' as default export, or export a 'const dynamicPluginInstaller: BackendDynamicPluginInstaller' field as dynamic loading entrypoint.","service":"backstage","timestamp":"2024-10-24 15:31:18"}
```

**Comment by PatAKnight** [comment]
Closing as #1818 already bumped 3scale plugin

**Pull request closed without merging**
