### PR TITLE
chore(deps): update argocd plugin version

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Description

Update ArogCD plugin version

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [x] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by Fortune-Ndlovu** [comment]
might need to run yarn install on the root directory

**Review by Fortune-Ndlovu — COMMENTED** [review]
you may need to run `yarn install` on the root directory and consider updating the dist-dynamic `package.json` also to `1.8.0`

**Comment by nickboldt** [comment]
```
After 'yarn install', workspace is dirty! The following files have changed:

app-config.example.yaml
app-config.yaml
yarn.lock
```

Please update these files so we can merge this PR.

**Comment by Fortune-Ndlovu** [comment]
LGTM, Can we merge this? cc: @nickboldt

**Review by Fortune-Ndlovu — APPROVED** [review]

**Comment by nickboldt** [comment]
@karthikjeeyar back to you for updating the argocd versions in  1.3.x ^

**Pull request merged**
