### PR TITLE
feat(kiali): add kiali dynamic plugin

### PR DESCRIPTION
**Pull request by aljesusg**
## Description

Add kiali plugin to showcase

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

1- In your local `backstage-plugins/plugins/kiali` and `backstage-plugins/plugins/kiali-backend`, run `yarn export-dynamic` to export RBAC plugin UI as a dynamic plugin
2 -In your local `backstage-showcase/dynamic-plugins-root/` directory, run the below command to install RBAC plugin UI

```bash
pkg=<local/path/to/backstage-plugins/plugins/kiali/>
pkgback=<local/path/to/backstage-plugins/plugins/kiali-backend/>
archive=$(npm pack $pkg)
tar -xzf "$archive" && rm "$archive"
mv package $(echo $archive | sed -e 's:\.tgz$::')
archiveback=$(npm pack $pkgback)
tar -xzf "$archiveback" && rm "$archiveback"
mv package $(echo $archiveback | sed -e 's:\.tgz$::')
```
The result in folder dynamic-plugins-root should be something like this
janus-idp-backstage-plugin-kiali-1.14.1  
janus-idp-backstage-plugin-kiali-backend-1.10.1
3- In your local `backstage-showcase/app-config.local.yaml` file, add the below changes

```yaml
...
# Kiali backend configuration
catalog:
  providers:
    kiali:
      url: '${KIALI_ENDPOINT}'
      serviceAccountToken: '${KIALI_SERVICE_ACCOUNT_TOKEN}'
      skipTLSVerify: true
# End kiali backend cofniguration
# Add this to enable Dynamic Plugins
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    janus-idp.backstage-plugin-kiali:
      appIcons:
        - name: kialiIcon
          importName: KialiIcon
      dynamicRoutes:
        - path: /kiali
          importName: KialiPage
          menuItem:
            icon: kialiIcon
            text: Kiali
      mountPoints:
        - config:           
            layout:
              gridColumn: "1 / -1"
            if:
              anyOf:
                - hasAnnotation: backstage.io/kubernetes-namespace
          importName: EntityKialiContent
          mountPoint: entity.page.kiali/cards
# End of Dynamic Plugins enablement config
```

4- In dynamic-plugins.default.yaml file Line 596, and Line 619  change disabled value to disabled: false to enable RBAC plugin UI.

```yaml
  - package: ./dynamic-plugins/dist/janus-idp-backstage-kiali
    disabled: false
...
 - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-kiali-backend-dynamic
    disabled: false
```
5 - Add a component with the annotation `backstage.io/kubernetes-namespace`
```yaml
# Example
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: istio
  description: An example of a Kiali demo istio-system.
  tags:
    - istio
    - kiali
    - core
    - servicemesh
  annotations:
    'backstage.io/kubernetes-namespace': istio-system,bookinfo
spec:
  type: service
  lifecycle: production
  owner: user:guest
```

6 - Start Backend-showcase app, and observe that Kiali button shows on the left side menu and the entity tab.

### CODE REVIEW

**Comment by davidfestal** [comment]
@christophe-f Do we really want to embed such a new plugin in the RHDH image and add a fixed new tab ?

**Comment by aljesusg** [comment]
> @christophe-f Do we really want to embed such a new plugin in the RHDH image and add a fixed new tab ?

we have customers already using the plugin (menu view) like dynamic plugin but they requested us to have some view for entity perspective

**Comment by davidfestal** [comment]
>  we didn't know that we have to add the plugin here to see kiali in the entity view

This shouldn't be. It's related to a limitation in the dynamic plugins support that we've just been discussing we should drop.

cc @christophe-f

**Comment by davidfestal** [comment]
Issue https://github.com/janus-idp/backstage-showcase/issues/1160 was opened for this purpose.

**Comment by gashcrumb** [comment]
With #1173 it will be possible to configure new tabs as needed in configuration.  Would you be willing to try this solution and see if this works for you?

**Comment by aljesusg** [comment]
If this work and it will be for next june release for us is fine. Anyway where is the place to add docs and kiali in RHDH docs? This is going to be a Openshift servicemesh plugin for customers supported and we want to include it

**Pull request closed without merging**
