### PR TITLE
chore(deps): update scalprum dependecies versions

### PR DESCRIPTION
**Pull request by Hyperkid123**
## Description

This is an issue with yarn and how its dependency deduplication works. The problems are exacerbated in mono repositories.

Why was this an issue?

The scallprum test utils package has the following scalprum core version requirement:
```
"scalprum/core": "^0.6.*"
```
Ant version `0.*.*` is compatible with the packages. However by locking the `@scalprum/core` dependency to `0.7.0` will result in the following dependency tree in the package:

```
yarn list --pattern @scalprum/core
yarn list v1.22.19
├─ @scalprum/core@0.6.6
└─ app@1.0.1
   └─ @scalprum/core@0.7.0
```
I've released versions that strictly require the latest versions of Scalprum. However, this is not an ideal solution. We might have to add yarn resolutions to ensure only actually installed packages is being used. OR switch to npm.

More information about the deduplication issues for nested dependencies can be found here: https://github.com/yarnpkg/yarn/issues/3778

### CODE REVIEW

**Review by gashcrumb — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@gashcrumb any idea why is the OCP/PR Test failing? I don't have access to the IBM cloud.

**Comment by gashcrumb** [comment]
Yep, lemme check, though I think at the moment it's expected that they'll fail.  I tested this locally and see no problem.

**Review by nickboldt — COMMENTED** [review]
This appears to be the opposite of https://github.com/janus-idp/backstage-showcase/pull/915 https://github.com/janus-idp/backstage-showcase/pull/912

but with an upgrade to "@scalprum/react-test-utils": "0.1.3"

@schultzp2020 @Zaperex

**Comment by Zaperex** [comment]
I just tested it locally, and it seems to work now. Not sure why the tests e2e-tests are failing at the moment as it seems like it wasn't able to access the UI?

**Review by schultzp2020 — APPROVED** [review]
I was told by QE that we can ignore the e2e tests for now. They don't have it fully setup. 

/lgtm

**Pull request merged**
