### PR TITLE
chore: enabled conditional rendering for the ArgoCD overview and history cards

### LINKED ISSUE #650: ArgoCD Overview and History Cards render when argocd annotation doesn't exist
### Describe the bug
ArgoCD Overview Card (in Overview tab) and ArgoCD History Card (in CD tab) appear even when the argocd annotations don't exist in the `catalog-info.yaml` of the component.
image
image

### Expected Behavior
The ArgoCD Overview and History Cards (Since CD tab is just the history card, it shouldn't appear either) should conditionally render depending on whether the argocd annotation exists for the component
image

### What are the steps to reproduce this bug?

1. Have a component entity registered into the catalog
2. Make sure component has no argocd annotations, and has spec.type as either website or service
3. Observe `Missing Annotation` error cards in place of argocd overview and history card

### PR DESCRIPTION
**Pull request by Zaperex**
## Description
Enabled conditional rendering for the ArgoCD overview and history cards based on presence of an argocd annotation
## Which issue(s) does this PR fix

- Fixes #650

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by schultzp2020** [comment]
@Zaperex has `isArgocdAvailable` been fixed?

**Comment by Zaperex** [comment]
I'm not sure what was wrong with it to begin with, since it was working when I tested it with the presence of `argocd/app-name` in the entity's annotations.

**Comment by schultzp2020** [comment]
@christophe-f do you remember why `isArgocdAvailable` wasn't working?

**Comment by christophe-f** [comment]
> @christophe-f do you remember why `isArgocdAvailable` wasn't working?

I believe that was a bug in the plugin. It could have been fixed since then.

**Comment by tumido** [comment]
This is solved by #700 

https://github.com/janus-idp/backstage-showcase/blob/7ed446586381fb437477076b686b68c5a37d9d16/dynamic-plugins.default.yaml#L276-L291

@Zaperex can we close this? WDYT?

**Comment by Zaperex** [comment]
Yep it makes sense to close this issue now

**Pull request closed without merging**
