### PR TITLE
Add Tekton plugin

### PR DESCRIPTION
**Pull request by debsmita1**
## Description

- Adds the Tekton plugin to the Showcase App. The CI tab of the App will display the latest pipeline run visualization if the tekton CI annotation (`janus-idp.io/tekton-enabled: 'true'`) is available.
- Updated the topology package version

## Which issue(s) does this PR fix

- Fixes https://github.com/janus-idp/backstage-showcase/issues/172

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

- Add ${K8S_CLUSTER_NAME} , ${K8S_CLUSTER_URL} ,  ${K8S_CLUSTER_TOKEN} info
- Create a pipeline run in the above cluster and ensure that the resource has the "backstage.io/kubernetes-id= test-backstage" label

## Screenshots
Screenshot 2023-05-03 at 3 40 56 PM

Screenshot 2023-05-04 at 10 14 08 PM

### CODE REVIEW

**Comment by christophe-f** [comment]
We don't need the `TEKTON_ENABLED` flag as there is no Tekton backend plugin. 

Once the code conflict is resolved we can merge it. 

Thanks @debsmita1 for the plugin and this PR

**Comment by debsmita1** [comment]
> We don't need the `TEKTON_ENABLED` flag as there is no Tekton backend plugin.
> 
> Once the code conflict is resolved we can merge it.
> 
> Thanks @debsmita1 for the plugin and this PR

I have also updated the Topology plugin package version in this PR. Let me know if that's okay or if I should raise a separate PR ?

**Comment by christophe-f** [comment]
> I have also updated the Topology plugin package version in this PR. Let me know if that's okay or if I should raise a separate PR ?

I usually prefer to have another PR just in case we need to revert something. But it's fine for this one.

**Review by christophe-f — APPROVED** [review]
LGTM

**Pull request merged**
