### PR TITLE
chore: [release-1.3] update 3scale references in dynamic-plugins-info

### PR DESCRIPTION
**Pull request by 04kash**
## Description

Updated configuration to reflect changes from https://github.com/janus-idp/backstage-showcase/pull/1514

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by JessicaJHee — APPROVED** [review]
LGTM, just need to wait for CI to pass

**Review by Fortune-Ndlovu — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
