### PR TITLE
feat(catalog): added created at column in the catalog page

### PR DESCRIPTION
**Pull request by debsmita1**
## Description

- The PR adds the scaffolder annotator action in the backend
- In the UI, the catalog page will now show a new `Created At` column for entity kind `Component`
- The new column can be sorted
- Has E2E test

## Which issue(s) does this PR fix

- Fixes 

https://issues.redhat.com/browse/RHIDP-2104
https://issues.redhat.com/browse/RHIDP-2193

## Screenshots/GIF

Screenshot 2024-05-14 at 1 42 25 PM

Screenshot 2024-05-14 at 1 33 38 PM

## Test setup

**Test setup:**

- Changes in `app-config.yaml`

```
catalog:
  location:
    # Example template
    - type: url
      target: https://github.com/debsmita1/nodejs-ex-1/blob/master/local-template.yaml
      rules:
        - allow: [Template]
```
- Use the `Create React App Template with timestamping` template to register the entity

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by subhashkhileri** [comment]
e2e tests changes looks good to me.

**Comment by Zaperex** [comment]
Tested this PR and the timestamp showed up as expected in the column:
image

**Review by ciiay — APPROVED** [review]
/lgtm

**Pull request merged**
