### PR TITLE
feat(notifications): introduce Notifications plugins to the showcase

### PR DESCRIPTION
**Pull request by mareklibra**
## Description

Adding the Notifications plugins to the show-case app.

- https://github.com/janus-idp/backstage-plugins/tree/main/plugins/notifications
- https://github.com/janus-idp/backstage-plugins/tree/main/plugins/notifications-backend

Screenshot from 2024-01-17 17-20-24

## TODO:
- [x] Have https://github.com/janus-idp/backstage-plugins/pull/1077 merged
- [x] rename dependencies from private NPM `@marek.libra/*` to `@janus-idp/*` once CI does its `npm publish`

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by davidfestal — CHANGES_REQUESTED** [review]
Do we really want to add this as a static plugin ?

cc @kadel

**Comment by mareklibra** [comment]
> Do we really want to add this as a static plugin

There is upstream work on the same feature in progress, we would ideally share (or build upon) what we have in Janus.
If we convert the plugin to a dynamic one here, we will deviate from the upstream even more.

Once the upstream Notifications land, it will be part of the core Backstage. And Janus will eventually rebase on top of the newer Backstage version.

**Comment by kadel** [comment]
> Do we really want to add this as a static plugin ?
> 
> cc @kadel

Not at this point. Especially not as a static plugin. We don't know what will happen in the upstream. 

@mareklibra Is there a reason why this couldn't be a dynamic plugin?

**Comment by davidfestal** [comment]
> > Do we really want to add this as a static plugin ?
> > cc @kadel
> 
> Not at this point. Especially not as a static plugin. We don't know what will happen in the upstream.
> 
> @mareklibra Is there a reason why this couldn't be a dynamic plugin?

Making it dynamic doesn't prevent it to be used as a static plugin, so wouldn't prevent it to be contributed to upstream at all.

**Comment by pkliczewski** [comment]
> Making it dynamic doesn't prevent it to be used as a static plugin, so wouldn't prevent it to be contributed to upstream at all.

@mareklibra if dynamic plugin could be used as static plugin I think it is safe to change it.

**Comment by mareklibra** [comment]
Closing the PR. The plugins are turned into dynamic ones.
I will file new PRs if further changes are needed.

**Pull request closed without merging**
