### PR TITLE
fix(ui): add pf5 button style config

### PR DESCRIPTION
**Pull request by ciiay**
## Description

A theme config for a Material-UI Button (v4) to look as similar as possible to a PF5 Button.

## Which issue(s) does this PR fix

- Fixes [RHIDP-1163](https://issues.redhat.com/browse/RHIDP-1163): Add MUI theme config so that Buttons looks similar to PF5

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
**Light theme buttons**:
light_buttons

Contained_button
light_contained_button_text_button
Contained_button_hover
light_contained_button_hover
Contained_button_disabled
light_contained_button_disabled
Outlined_button
light_outlined_button
Outlined_button_hover
light_outlined_button_hover
Text_button
light_text_button
Text_button_hover
light_text_button_hover

**Dark theme buttons**:
Contained button and text button:

https://github.com/janus-idp/backstage-showcase/assets/26255262/308cff15-0036-4def-95b7-e82c4265c2fb

Contained_button_disabled
dark_contained_button_disabled
Outline_button
dark_outline_button
Outline_button_hover
dark_outline_button_hover

Dark theme palette reference:
https://www.patternfly.org/developer-resources/dark-theme-handbook/
https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/themes/dark/scss-variables.scss
https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/themes/dark/colors.scss

### CODE REVIEW

**Comment by ShiranHi** [comment]
@ciiay that looks great, thank you! 
I have 2 questions:

1. It appear that the button's dark theme color differs between light and dark modes? From what I saw, it should remain the same shade of blue, shouldn't it?
image

2. Is there a way to improve the visibility of the disabled "Contained_button_disabled" button in dark mode? It seems to blend too much with the background color. Is there something we can do? could we adjust the background color to make the button stand out more?
image2

**Review by gashcrumb — APPROVED** [review]
This looks great!  If the dark theme card background is a separate issue I think this is good to go.  :+1: 

Well, and probably this will need a changeset added too @ciiay

**Review by gashcrumb — APPROVED** [review]

**Comment by ShiranHi** [comment]
> 1. According to the **Blue color palette** on PF5 [dark theme handbook](https://www.patternfly.org/developer-resources/dark-theme-handbook/) documentation, the primary blue (blue-300) gets updated for the dark theme. You can also check the updated color code in [here](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/themes/dark/scss-variables.scss#L16C37-L16C57) and [here](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/themes/dark/colors.scss#L16). Let me know if we want to keep the original primary blue in dark theme. Here's a preview of it.
>
I see, then let's follow the PF guidelines. I am a bit confused because when I switch between the bright and dark mode on the [PF page](https://www.patternfly.org/components/button) (top right corner), the blue color stays the same.  

> Our current card background color doesn't match the [PF5 value](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/themes/dark/scss-variables.scss#L3). @jerolimov and I discussed about this issue and we're going to create a ticket to update the card style to match PF5. Then the disabled contained button would look good. Here's a preview.
>
Thanks for the update, the card with the PF5 style in dark theme looks great!

>Also there's a [demo](https://www.patternfly.org/patterns/dashboard/html-demos/basic/) for PF5 style we can refer, and the sidebar menu color in dark theme looks pretty different from our current one. You can toggle theme using the bottom right button. Let us know if we want to match it or keep our current style. Thanks.
>
Yes, let's follow this demo. I think this is what @debsmita1 is working on in [this PR](https://github.com/janus-idp/backstage-showcase/pull/960#issue-2127616164)

**Comment by ciiay** [comment]
Hi @ShiranHi , as confirmed with the PF team, the contained button background stays the same color in dark theme as the light theme. I have updated a screen video to show the updated style. Here's how it looks now.
updated_contained_button_bg_color
Hover:
updated_contained_button_bg_color_hover

**Review by gashcrumb — APPROVED** [review]

**Review by gashcrumb — APPROVED** [review]

**Comment by ShiranHi** [comment]
@ciiay thanks for making those adjustments! lgtm

**Comment by jerolimov** [comment]
Hi, this looks like a step into the right direction. Here are two recordings where I've tested MUI v4 and v5 buttons with the default Janus and the RHDH theme.

**Main branch:**

https://github.com/janus-idp/backstage-showcase/assets/139310/fbafa1d4-b867-495f-8678-26e4fc02cd8a

**With this PR:**

https://github.com/janus-idp/backstage-showcase/assets/139310/b823bb1b-35fe-42ae-a592-4070b952b61e

I saw a minor issue: the shadow is only removed from primary buttons, not secondary ones.

In the long term, we should use the palette colors from the team instead of creating a new palette of colors!

For me, it's fine to merge this because we also didn't use the primary color from app-config.yaml for buttons before.

**Comment by jerolimov** [comment]
To test if I can add approval ...

/approve
/lgtm cancel

**Comment by ciiay** [comment]
@jerolimov Thanks for the review. I have updated this PR to address your feedback. Please take a look.

**Review by jerolimov — APPROVED** [review]
Thanks for the update! Lgtm! :+1:

/lgtm

**Pull request merged**
