### PR TITLE
feat(deps): replace bundled themes with RHDH theme

### PR DESCRIPTION
**Pull request by jerolimov**
## Description

Switch to new NPM packages that extract our RHDH theme.

* https://github.com/redhat-developer/red-hat-developer-hub-theme
* https://npmjs.com/package/@redhat-developer/red-hat-developer-hub-theme

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-1169

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by ciiay** [comment]
Hi @jerolimov , I have tested it out and it works perfectly ✨  Thank you 👏 👏 

I have two PRs #1168 #1171  open for style matching for now, once they get merged I can migrate the latest `componentOverrides.ts` and `defaultThemePalette.ts` into [red-hat-developer-hub-theme](https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main)/[src](https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src)/[themes](https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src/themes)/[rhdh](https://github.com/redhat-developer/red-hat-developer-hub-theme/tree/main/src/themes/rhdh) then get rid of `componentOverrides.ts` and `defaultThemePalette.ts` from this repo.

**Comment by invincibleJai** [comment]
@jerolimov the job seems to fail with the below failure 

 ```
      @redhat-developer/red-hat-developer-hub-theme must be declared in devDependencies of plugins/analytics-module-matomo/package.json, run 'yarn --cwd plugins/analytics-module-matomo add --dev @redhat-developer/red-hat-developer-hub-theme' from the project root
  
  
       plugins/analytics-module-matomo/dev/index.tsx:5:1
       3 | import { createDevApp } from '@backstage/dev-utils';
       4 | 
     > 5 | import { createDevAppThemes } from '@redhat-developer/red-hat-developer-hub-theme';
         | ^
       6 | 
       7 | import { analyticsModuleMatomoPlugin } from '../src';
       8 | import { Playground } from './Playground';
  
  ✘ 1 problem (1 error, 0 warnings)
```

https://github.com/janus-idp/backstage-plugins/actions/runs/8833415969/job/24371757247?pr=1480#step:3:362

**Comment by invincibleJai** [comment]
@jerolimov some ci jobs are failing can you pls look into this and rebase?

**Comment by gashcrumb** [comment]
Testing this out locally and it looks great!  One thing I've noticed today and I'm not sure if it's this PR or the theme but there's been a persistent bottom scroll bar visible on the window:

image

**Review by gashcrumb — APPROVED** [review]

**Comment by ciiay** [comment]
@gashcrumb I'm testing on mac and not able to reproduce this persistent scrollbar
image

**Pull request merged**
