### PR TITLE
add msgraph-transformer module

### PR DESCRIPTION
**Pull request by JessicaJHee**
## Description

The default user transformer provided by the [MsGraph plugin](https://github.com/backstage/backstage/tree/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/catalog-backend-module-msgraph#readme) does not ingest users who do not have an email included in their profile, preventing those users from signing in. This is an issue because email is not a mandatory field when creating an user and therefore not all users will have this field defined.

This module [customizes the entity provider](https://github.com/backstage/backstage/tree/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/catalog-backend-module-msgraph#customize-the-processor-or-entity-provider) by implementing the `microsoftGraphOrgEntityProviderTransformExtensionPoint` to allow users without an email to be ingested into the catalog by using `userPrincipalName` as the identifier, instead of email by default.
* The `userPrincipalName` parameter is must exist for each user and is unique.
## Which issue(s) does this PR fix

- Fixes/ result of [RHIDP-3209](https://issues.redhat.com/browse/RHIDP-3209)

## PR acceptance criteria
1. Add an Microsoft Entra ID user without email
2. [Set up](https://github.com/backstage/backstage/tree/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/catalog-backend-module-msgraph#getting-started) the `microsoftGraphOrg` entity provider as normal. 
3. Verify that they are ingested into the catalog and that the `entityRef` is the `userPrincipalName`

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
Testing requires setting up a MS Entra ID and creating an application with read permissions on reading users/groups.

### CODE REVIEW

**Comment by nickboldt** [comment]
/retest

@JessicaJHee Should the addition of this new package require the addition of any related tests? cc: @josephca  FYI

**Comment by JessicaJHee** [comment]
> @JessicaJHee Should the addition of this new package require the addition of any related tests? cc: @josephca FYI

@nickboldt I'll look into writing tests for the transformer 👍

**Pull request closed without merging**
