### PR TITLE
chore(rbac): update e2e test for bug fix

### PR DESCRIPTION
**Pull request by ciiay**
## Description

Added a text verification for rbac RoleList page after updated a role. This is for [RHIDP-1362](https://issues.redhat.com//browse/RHIDP-1362).
**Also fixed a bug of e2e tests `checkAndReauthorizeGithubApp` function.**

## Which issue(s) does this PR fix

- Fixes [RHIDP-1362](https://issues.redhat.com/browse/RHIDP-1362)
- Related to [PR](https://github.com/janus-idp/backstage-plugins/pull/1354) in backstage-plugins repo.

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [x] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

pr_1090_e2e_test

### CODE REVIEW

**Comment by debsmita1** [comment]
The test case is passing

Screenshot 2024-03-28 at 7 03 24 PM

Thank you @ciiay !!

Please rebase and push again.

**Comment by invincibleJai** [comment]
/approve

verified the changes locally, this works as expected

**Pull request merged**
