### PR TITLE
fix(homepage): wrapper update (incl update @scalprum/react-core from 0.8 to 0.9)

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Description

* This updates the `dynamic-home-page` dependency to include @kim-tsao PR https://github.com/janus-idp/backstage-showcase/pull/1977 after we migrated the plugin to rhdh-plugins repo.
* ~~Also removed the default home page and added it to the dynamic-plugins.default.yaml. When a user disables the dynamic home page, also the menu item will disappear automatically.~~

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by christoph-jerolimov** [comment]
Tested this on a cluster and the home page wasn't loaded anymore! :disappointed:

/hold

**Comment by christoph-jerolimov** [comment]
> Tested this on a cluster and the home page wasn't loaded anymore! 😞

I mixed two tests and had `disabled: true` in my tests. All fine! :smile: 

I've verified [pr-1969-1cc76bf4](https://quay.io/janus-idp/backstage-showcase:pr-1969-1cc76bf4) now on a cluster:

Default:

image

With some configuration:

image

Just disabled plugin:

image


Disabled plugin with hidden menu item via:

```yaml
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page
        disabled: true

upstream:
  backstage:
    image:
      # ...

    appConfig:
      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.home:
                title: ""
```

image

/hold cancel

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Comment by christoph-jerolimov** [comment]
As far as I checked are all failures related to infrastructure issues. I'm sorry but I'll bypass that tests now.

/override ci/prow/e2e-tests

**Pull request merged**
