### PR TITLE
Add Janus Theme and logos

### LINKED ISSUE #8: Add Theme / Customization
Story
- As a user, I wish to see the Janus IDP related themes within the Backstage Showcase app.

Description
- Backstage allows for the default themes to be overridden allowing users to customize the look and feel of their app. We can leverage this to create themes focused around our brand. 

AC
- Implement the agreed upon themes that were decided by the Janus IDP team.

Additional Notes 
- We will need to have some conversations around how we want the Backstage Showcase app to look and feel.

### PR DESCRIPTION
**Pull request by christophe-f**
## What does this PR do / why we need it

Add Janus theme and logos to the showcase app

## Which issue(s) does this PR fix

Fixes #8

## PR acceptance criteria

- [ ] Unit Tests
- [ ] E2E Tests
- [ ] Documentation

### CODE REVIEW

**Review by schultzp2020 — COMMENTED** [review]
I think the `packages/app/public/safari-pinned-tab.svg` svg has too much whitespace.

**Comment by christophe-f** [comment]
Updated the svg size

**Comment by christophe-f** [comment]
yes, we can create a section on the website with the assets.

**Comment by schultzp2020** [comment]
> Updated the svg size

The svg still looks like it has too much whitespace on the right and the bottom.

**Review by schultzp2020 — APPROVED** [review]

**Pull request merged**
