### PR TITLE
feat: add devtools frontend and backend plugin to showcase

### LINKED ISSUE #480: Add devtools-backend plugin
### What do you want to improve?

We need to add the devtools-backend plugin:
https://github.com/backstage/backstage/blob/53b916f7a8f788893e42c4aa61f66b4628b54850/plugins/devtools-backend/README.md

### PR DESCRIPTION
**Pull request by Zaperex**
## Description

Add the devtools [backend](https://github.com/backstage/backstage/tree/master/plugins/devtools-backend) and [frontend](https://github.com/backstage/backstage/tree/master/plugins/devtools) plugin to the showcase

## Which issue(s) does this PR fix

- Fixes #480

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by Zaperex** [comment]
I added the devtools frontend plugin as well, since the backend plugin only provides the data via API endpoints.

**Comment by Zaperex** [comment]
Also, do we want to modify the frontend plugin to utilize the permissions framework?
https://github.com/backstage/backstage/tree/master/plugins/devtools#permissions

**Comment by gorkem** [comment]
Is it decided if permissions will be enabled for this? My preference is that we have them enabled.

**Comment by Zaperex** [comment]
I just enabled the permissions framework for now. If no permission policy related to it is defined, it'll work as if the permission framework isn't there.

**Review by nickboldt — CHANGES_REQUESTED** [review]
needs to be rebased.

**Comment by schultzp2020** [comment]
@Zaperex I am closing because this PR will need to change to a dynamic plugin wrapper.

**Pull request closed without merging**
