### PR TITLE
[e2e-tests] Update and Fix tests (ocm & dynamic plugins info)

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Description

[e2e-tests] Update and Fix tests (ocm & dynamic plugins info)

## Which issue(s) does this PR fix

https://issues.redhat.com/browse/RHIDP-1335

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by gashcrumb — APPROVED** [review]

**Review by gashcrumb — APPROVED** [review]

**Comment by gashcrumb** [comment]
Looks like something's up with one of the actions; I don't see an error in the build output.  Did it time out?

**Comment by subhashkhileri** [comment]
> Looks like something's up with one of the actions; I don't see an error in the build output. Did it time out?

I see operation Canceled error. not sure if its due to timeout.
```
#24 698.5 backstage-plugin-tech-radar:export-dynamic: Loaded config from app-config.yaml
Error: The operation was canceled.
```

**Comment by gashcrumb** [comment]
Not sure if this is at all related but this doesn't seem good is this a known thing:

image

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Comment by gashcrumb** [comment]
Surprising this hasn't failed the build:

```
ERROR: failed to solve: error writing layer blob: failed to copy: failed to send write: write /tmp/.buildx-cache-new/ingest/ea824dd0ad11643b0d67c96b7b958aaa98ad0b09a8bd75f446ae5403d99ef284/data: no space left on device: unknown
```

**Pull request merged**
