### PR TITLE
test(e2e): enforce naming

### PR DESCRIPTION
**Pull request by nilgaar**
## Description

Enforcing naming conventions on files and code elements

## Which issue(s) does this PR fix

- Fixes (https://issues.redhat.com/browse/RHIDP-4243

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by nilgaar** [comment]
besides the naming convention, I am adding the fixes for the Sonar alerts https://sonarcloud.io/summary/new_code?id=janus-idp_backstage-showcase&pullRequest=1906 into the PR in order to pass the analysis

**Comment by josephca** [comment]
/lgtm
/approve

It's almost impossible to review all files  :) but the refactoring for the naming convention was LGTM

**Pull request merged**
