### PR TITLE
fix(homepage): fix todos and add support for top and recently visited cards

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Description

1. Top visited cards and recently visited cards works now
   * `VisitListener` must be added to `AppBase`
   * Wrapped the home page plugin VisitListener so that it's got only mounted if the admin configures a `RecentlyVisitedCard` or a `TopVisitedCard`.
   * Created [RHIDP-4234](https://issues.redhat.com//browse/RHIDP-4234) to replaced this code later with a mount point (the mount point doesn't exist yet)
2. Fixed the dev pages
   * Added missing catalog pages so that the starred entities card works as expected
   * Removed a todo
3. Changed the sort order for the priority of cards so that it's aligned with the sidebar priority
   * The priority field was not documented yet, so it should be fine to change it.
   * I like to backport that change anyway if we want release a 1.3.x version.
4. Featured docs card uses a lowercase " Learn more" button now instead of "LEARN MORE".
5. Quick access card: Added NOSONAR and added a note why

## Which issue(s) does this PR fix

- Fixes [RHIDP-4133](https://issues.redhat.com/browse/RHIDP-4133)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

1. Test the default home page
2. Test the customized home page with the touched cards:

```yaml
dynamicPlugins:
  frontend:
    janus-idp.backstage-plugin-dynamic-home-page:
      mountPoints:
        - mountPoint: home.page/cards
          importName: TopVisitedCard
        - mountPoint: home.page/cards
          importName: RecentlyVisitedCard
        - mountPoint: home.page/cards
          importName: FeaturedDocsCard
```

### CODE REVIEW

**Review by ciiay — APPROVED** [review]
Verified the PR image on OCP v4.15 cluster and it worked as expected.

https://github.com/user-attachments/assets/51cfd80f-2ebc-4b84-a186-d6497f7eaf27


https://github.com/user-attachments/assets/e2a305b2-c9ea-49f2-9c87-acb3be941fa5

/lgtm

**Review by invincibleJai — APPROVED** [review]
/approve

**Review by ciiay — APPROVED** [review]
/lgtm

**Comment by nickboldt** [comment]
Spoke to Christoph; this is not for 1.3.z, only 1.4+

**Comment by christoph-jerolimov** [comment]
Will test it on a cluster, hold until I've verified the latest changes.

/cc @invincibleJai 
/hold

**Comment by christoph-jerolimov** [comment]
> The image is available at:
> 
> * [`quay.io/janus-idp/backstage-showcase:pr-1724`](https://quay.io/janus-idp/backstage-showcase:pr-1724) or
> * [`quay.io/janus-idp/backstage-showcase:pr-1724-f21c67e2`](https://quay.io/janus-idp/backstage-showcase:pr-1724-f21c67e2)

Tested with this build:

https://github.com/user-attachments/assets/df0531b7-9b85-4669-b74c-fc433dd66630

/unhold

**Comment by ciiay** [comment]
/lgtm

Thank you 🤝

**Pull request merged**
