### PR TITLE
Update Yarn, Node and dependencies

### LINKED ISSUE #880: Upgrade to Node 20
Node 18 is in maintenance. Node 20 is the current LTS. 

### Which dependency needs to be upgraded?

Node 20

### What is the current version of the dependency?

Node 18

### Which version to upgrade to?

Node 20

### 

With node 20, there are dependencies to update. 

```
backstage-showcase % yarn install
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error @azure/msal-node@1.18.3: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18". Got "20.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### PR DESCRIPTION
**Pull request by taliesins**
## Description

Updated to the Yarn 4.1.1, Node 20 and update package dependencies

Also update Dockerfiles and github workflow steps to use the latest versions.

Needed to update to the latest version of Yarn sytanx

## Which issue(s) does this PR fix

- Fixes #880 

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [x] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by davidfestal** [comment]
For a number of reasons, I'm not sure we want to move to yarn 4 for now.

@nickboldt @kadel Do you confirm ?

**Comment by kadel** [comment]
> For a number of reasons, I'm not sure we want to move to yarn 4 for now.

Yarn 4 is definitely on our roadmap,  but we can't update it right now due to limitations in our build system. We need to resolve those first.

**Comment by kadel** [comment]
There should not be any external blockers for moving to node 20, but there were some fixable issues. @BethGriggs was looking into that.

**Comment by taliesins** [comment]
Which limitations in the build system? I think I managed to fix all of the local builds and Docker ones?

**Comment by taliesins** [comment]
@davidfestal and @kadel I have fixed the build part now. What do I need to do about getting SonarCloud gate passing as its not really code I have touched.

**Review by nickboldt — CHANGES_REQUESTED** [review]
Unfortunately we cannot move to Yarn v4 at this time, for two reasons:

* downstream RHDH build process requires Yarn v1 today and v3 in future
* upstream Backstage community-plugins repo will use Yarn v3, not 4. 

Can you revise this PR to use Node 20, but stick with yarn 1.22.22 ? 

cc: @schultzp2020

**Comment by davidfestal** [comment]
> Can you revise this PR to use Node 20, but stick with yarn 1.22.22 ?

Please be aware that the work of migrating to Node 20 has already been implemented in the following PR: https://github.com/janus-idp/backstage-showcase/pull/1048

**Comment by davidfestal** [comment]
> > Can you revise this PR to use Node 20, but stick with yarn 1.22.22 ?
> 
> Please be aware that the work of migrating to Node 20 has already been implemented in the following PR: #1048

cc @BethGriggs

**Comment by taliesins** [comment]
The whole thing that started me down this path was the large amount of time that it took to build this solution so that I could containerize it. On my work machines with security tools it was taking my 58 minutes to build. I had to remote into my home machine (4th gen nvme, 128GB of ram & Ryzen 5950x) to build anything. Yarn 4 is significantly faster then Yarn 1 on my machine.

Have a look at another PR like #1133 it took 31 minutes vs the 17 minutes this one takes for the "PR Docker Build / PR Docker Build (pull_request_target)" step.

**Comment by nickboldt** [comment]
Won't do. We plan to move to Yarn 3 later this year to align with Backstage's community-plugins repo, and to start using Konflux. But that doesn't support Yarn 4, so we don't be able to accpet this PR for some time.

**Pull request closed without merging**
