### PR TITLE
feat(app): Add dark theme support

### PR DESCRIPTION
**Pull request by divyanshiGupta**
## Description

Currently showcase app only supports light theme (https://github.com/janus-idp/backstage-showcase/pull/17). This PR aims to add a dark theme based on the existing light theme. In the existing light theme only the navigation color palette is customised so following the same, this PR customises the navigation color palette based on pf v5 color palette (as suggested by UX). 
This PR also adds a dark theme button in the settings page and also updates the light/dark theme icons.

## Which issue(s) does this PR fix

- Fixes https://github.com/janus-idp/backstage-showcase/issues/513

## Screenshots/recording:

https://github.com/janus-idp/backstage-showcase/assets/20724543/2b180505-695a-4318-afd9-0f98c9bf6912

Screenshot 2023-09-13 at 7 11 40 PM

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @invincibleJai @gashcrumb

**Comment by divyanshiGupta** [comment]
cc: @ShiranHi

**Review by gashcrumb — APPROVED** [review]
LGTM :+1:  and I agree this seems like a minor change.

**Review by christophe-f — APPROVED** [review]
lgtm

**Pull request merged**
