### PR TITLE
feat(licensed-users): introduce licensed user info plugin

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
## Description

Introduce licensed user info plugin. This plugin provides information with list recorded logged in users and quantity of these users.

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-3603

### How to test it

Configure instance: apply your user to the list permission policies admins.

1. Execute instance.
2. Log in with help of one of the auth providers, GitHub for example.
3. Retrieve token.
4. Make requests:

```bash
curl -X GET "http://localhost:7007/api/licensed-users-info/users/quantity" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
```

Example of the response:

```
{"quantity":"2"}
```

```bash
curl -X GET "http://localhost:7007/api/licensed-users-info/users" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
```

Example of the response:

```
[{"userEntityRef":"user:default/cyber-stalker-bit","lastTimeLogin":"Thu, 22 Aug 2024 13:25:46 GMT","email":"marketo0user@gmail.com"},{"userEntityRef":"user:default/andrienkoaleksandr","lastTimeLogin":"Thu, 22 Aug 2024 13:26:08 GMT","displayName":"Oleksander Andriienko","email":"oandriie@redhat.com"}]
```

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by PatAKnight** [comment]
For the failing docker build, you will need to update the Dockerfiles. It should look something like this
`COPY $EXTERNAL_SOURCE_NESTED/plugins/licensed-users-info-backend/package.json ./plugins/licensed-users-info-backend/package.json` and will need to added to this [Dockerfile](https://github.com/janus-idp/backstage-showcase/blob/main/.rhdh/docker/Dockerfile#L56) and this [Dockerfile](https://github.com/janus-idp/backstage-showcase/blob/main/.rhdh/docker/Dockerfile#L56). I would also update the [.dockerignore](https://github.com/janus-idp/backstage-showcase/blob/main/.dockerignore#L9) and add the plugin there as well.

You can see what I did in this [PR](https://github.com/janus-idp/backstage-showcase/pull/1072/files) where I added the OIDC auth plugin module.

**Comment by kadel** [comment]
I'm using 1.29.2, but I'm still getting `no such table: user_info"`  When is this table created?

**Comment by kadel** [comment]
When I'm not getting error about not-existing table I get he following error :-( 
```
{"error":{"name":"TypeError","message":"userInfoRow.exp.getTime is not a function","stack":"TypeError: userInfoRow.exp.getTime is not a function\n    at rowToResponse (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:120:23)\n    at userInfoRow (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:78:7)\n    at Array.map (<anonymous>)\n    at <anonymous> (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:77:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"GET","url":"/users"},"response":{"statusCode":500}}%
```

**Comment by kadel** [comment]
> When I'm not getting error about not-existing table I get he following error :-(
> 
> ```
> {"error":{"name":"TypeError","message":"userInfoRow.exp.getTime is not a function","stack":"TypeError: userInfoRow.exp.getTime is not a function\n    at rowToResponse (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:120:23)\n    at userInfoRow (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:78:7)\n    at Array.map (<anonymous>)\n    at <anonymous> (/Users/tkral/Code/backstage-showcase/plugins/licensed-users-info-backend/src/service/router.ts:77:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"GET","url":"/users"},"response":{"statusCode":500}}%
> ```

It looks like this is related to using sqlite as database. When I switched to PostgreSQL I don't see any issues

**Comment by PatAKnight** [comment]
@kadel Yeah, this is an issue that we run into with the RBAC backend plugin as well. For some reason, whenever you are establishing a connection to another plugin's database, there are issues when using sqlite. However, it works properly when using postgres.

**Comment by AndrienkoAleksandr** [comment]
@kadel we can make this plugin working with sqlite in memory configuration, but in this case I need to wrap auth plugin. See patch to achieve this goal:

https://github.com/AndrienkoAleksandr/backstage-showcase/pull/1

But I'm not sure if we would like to do that in the current development iteration. What do you think @PatAKnight ?

**Comment by AndrienkoAleksandr** [comment]
@kadel I fixed sqlite configuration with directory storage in the current pull request.

**Pull request merged**
