### PR TITLE
docs: update OpenTelemetry set up documentation

### PR DESCRIPTION
**Pull request by JessicaJHee**
## Description

Updates the metrics set up documentation to reflect the new behaviour after adopting OpenTelemetry in [this PR](https://github.com/janus-idp/backstage-showcase/pull/1811)

## Which issue(s) does this PR fix

[RHIDP-4404](https://issues.redhat.com/browse/RHIDP-4404)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by JessicaJHee** [comment]
waiting for [this PR](https://github.com/redhat-developer/rhdh-operator/pull/409) to be accepted.

**Review by kim-tsao — APPROVED** [review]

**Comment by kim-tsao** [comment]
I'm going to force merge this as it's just a docs update

**Pull request merged**
