### PR TITLE
[WIP] deps(homepage): update upstream home plugin dependencies

### PR DESCRIPTION
**Pull request by jerolimov**
## Description

Update to the latest upstream home page plugin.

> [!CAUTION]
> This PR is primarily to test the upgrade that introduced some home page plugin issues the last time!
>
> It might break that the sidebar and home page aren't configurable anymore!
>
> I mark this as WIP or hold until we tested this on a cluster.

## Which issue(s) does this PR fix

* [RHIDP-4129 - Investigate how (home page) dependency updates breaks dynamic plugins (config isn't loaded)](https://issues.redhat.com/browse/RHIDP-4129)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

* Customize the sidebar as described in #1507 and #1578
* Customize the homepage as described in #1532

### CODE REVIEW

**Comment by jerolimov** [comment]
/cc @gashcrumb 
fyi @ciiay @invincibleJai

**Comment by gashcrumb** [comment]
Seems to work for me.  Also I think a bunch of the e2e tests effectively rely on the configuration loading properly on the frontend or they won't pass.

**Comment by nickboldt** [comment]
tests pass, @gashcrumb is happy, so merging. 

I'm assuming this is NOT to be picked to the release-1.3 branch?

**Comment by jerolimov** [comment]
Oh, sorry, this PR was for testing purposes only. But I can confirm that the customizable sidebar and home page still work fine. :+1: 

Maybe because @gashcrumb improved the shared libraries?

So its fine that we merged it, but we should not merge it into 1.3 without additional testing. :smirk:

**Comment by gashcrumb** [comment]
> So its fine that we merged it, but we should not merge it into 1.3 without additional testing. 😏

Ah, probably should keep these kinds of things in Draft so it's clear, then it's definitely not merge-able.

**Comment by nickboldt** [comment]
> keep these kinds of things in Draft so it's clear

Yeah so trigger-happy idjits like me don't merge stuff too fast :D

**Pull request merged**
