### PR TITLE
feat: disabled telemetry by default

### PR DESCRIPTION
**Pull request by kadel**
## Description

disabling telemetry by default.

User needs to enable it (opt-in)

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]
+100

**Comment by nickboldt** [comment]
Related change to the doc PR: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/212#pullrequestreview-2082819253

**Comment by kadel** [comment]
After another set of discussions we are keeping it as opt-out (enabled by default)

**Pull request closed without merging**
