### PR TITLE
docs: Document installation on EKS using Helm and Operator and integration with AWS services for auth, monitoring and logging

### PR DESCRIPTION
**Pull request by rm3l**
## Description

This documents installation and integration on AWS when installing using either the Helm Chart or the Operator.

- Installation on EKS clusters using Helm or Operator
- Integration with AWS CloudWatch Logs for logging
- integration with Amazon Managed Service for Prometheus for monitoring metrics
- Using AWS Cognito as auth provider (through the built-in `oidc` provider)

## Which issue(s) does this PR fix

- Related to https://issues.redhat.com/browse/RHIDP-1065 (Epic)
  - Related to https://issues.redhat.com/browse/RHIDP-1081 (Story covering the Helm Chart)
  - Related to https://issues.redhat.com/browse/RHIDP-1068 (Story covering the Operator)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
- Requires an AWS account.
- Follow the documentation in this PR to try it out

### CODE REVIEW

**Comment by kadel** [comment]
@rm3l Keep in mind that for RHDH you will also need to create PullSecret and configure helm chart to use to in order to download images from RH container registry

**Comment by rm3l** [comment]
> @rm3l Keep in mind that for RHDH you will also need to create PullSecret and configure helm chart to use to in order to download images from RH container registry

@kadel I've added those instructions in a separate document for downstream RHDH. This GDoc can be used later on as a starting point by the docs team. See https://docs.google.com/document/d/1MWPIaehSAIH-B_peV4UgHuuER-3ZgSbLSLQxomDRfuE/edit
PTAL. Thanks.

**Comment by rm3l** [comment]
/hold

I'll update this PR accordingly after the docs team merges the downstream version. We are iterating on the corresponding doc.

**Comment by kadel** [comment]
@rm3l is this aligned with downstream docs, can we merge it?

**Comment by rm3l** [comment]
> @rm3l is this aligned with downstream docs, can we merge it?

@kadel Yes, this is aligned with downstream docs and can be merged. Thanks!

**Comment by rm3l** [comment]
/override "PR Docker Build"

Doc-only PR

**Comment by rm3l** [comment]
/override "PR Docker Build"

Doc-only PR

**Comment by nickboldt** [comment]
@rm3l I'm assuming this is outdated because we already have doc in https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html-single/installing_red_hat_developer_hub_on_amazon_elastic_kubernetes_service/index for installation and all three linked jIRAs are closed.

**Pull request closed without merging**
