### PR TITLE
[1.3.x] chore(deps): bump tekton and quay plugin

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This is a manual cherry-pick of https://github.com/janus-idp/backstage-showcase/pull/1628

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
cc: @nickboldt

**Review by Eswaraiahsapram — APPROVED** [review]

**Review by jerolimov — APPROVED** [review]

**Comment by karthikjeeyar** [comment]
E2e tests were passing earlier https://prow.ci.openshift.org/pr-history/?org=janus-idp&repo=backstage-showcase&pr=1629 now it shows unrelated errors with GIthub account errors.

**Pull request merged**
