### PR TITLE
fix(gitlab): add a dynamic wrapper to expose the gitlab org provider

### PR DESCRIPTION
**Pull request by PatAKnight**
## Description

Adds a dynamic plugin wrapper of the Gitlab backend catalog module that exposes the Gitlab org provider.

## Which issue(s) does this PR fix

- Fixes (https://issues.redhat.com/browse/RHIDP-1480)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

I haven't been able to successful test this yet. I am assuming that I am having problems with my Gitlab setup. Figured I will go ahead and get this PR posted in case someone else can successful test against it.

### CODE REVIEW

**Review by davidfestal — APPROVED** [review]

**Comment by davidfestal** [comment]
@PatAKnight Do you think you could have a look at the CI Main Job failure ?

**Comment by PatAKnight** [comment]
@davidfestal It looks like the PR upstream has been merged, so I will update this to use the new GitLab Org module and will take a look at the failing CI while I am at it.

**Comment by davidfestal** [comment]
>  so I will update this to use the new GitLab Org module

You may need to add the new events support, before doing the switch since, afair, this PR added a dependency to the events service (or plugin).

**Pull request merged**
