### PR TITLE
chore(deps): update RHDH theme

### PR DESCRIPTION
**Pull request by jerolimov**
This PR updates the theme to the latest version, which includes improvements and bugfixes. Esp. this changes:

1. The Red Hat font is now also part of the package and used for text, headlines and code blocks.
2. The headline font sized are a bit more aligned with PF
3. Removed underlines from the main navigation
4. Tab and content is more alignment on the settings page
5. Padding between cards on the home page is more aligned, for this I removed some special rules that works not well with all card sizes
6. Cards border color like PF6 (as Christophe requested today)
7. Added the 1px line below the header (as Christophe requested today) -- But it's also shown when when the tabs appear, so hmm..
8. Removed "always uppercase" from ToggleButtons (as we had this already for Buttons, for example on the settings page when selecting a theme)

Here are some screenshots to compare some of these changes:

## Light

| Backstage | Old theme | New theme |
|----|----|----|
| 3-catalog-backstage-light | 3-catalog-rhdh-light | 3-catalog-rhdh-light |
| 4-catalog-entry-backstage-light | 4-catalog-entry-rhdh-light | 4-catalog-entry-rhdh-light |
| 8-settings-backstage-light | 8-settings-rhdh-light | 8-settings-rhdh-light |

## Dark

| Backstage | Old theme | New theme |
|----|----|----|
| 3-catalog-backstage-dark | 3-catalog-rhdh-dark | 3-catalog-rhdh-dark |
| 4-catalog-entry-backstage-dark | 4-catalog-entry-rhdh-dark | 4-catalog-entry-rhdh-dark |
| 8-settings-backstage-dark | 8-settings-rhdh-dark | 8-settings-rhdh-dark |

### CODE REVIEW

**Comment by debsmita1** [comment]
tested it locally
/lgtm

**Comment by debsmita1** [comment]
/lgtm cancel
Wanted to add the label to the PR on the backstage-plugins repo

**Comment by ciiay** [comment]
Hi @jerolimov , only one standing out alignment issue. I have left a comment in the theme repo commits of the cause of this. The rest looks great to me. Thank you.
image

**Review by ciiay — COMMENTED** [review]
This PR itself looks good. Just need some updates in the theme repo. Probably upgrade theme repo first then update the theme package version here.

**Comment by ShiranHi** [comment]
looks good to me @jerolimov, thank you to everyone who has been involved

**Comment by jerolimov** [comment]
> Hi @jerolimov , only one standing out alignment issue. I have left [a comment](https://github.com/redhat-developer/red-hat-developer-hub-theme/commit/b8a4cd8b81d49168dddaddd260661be4686d244f) in the theme repo commits of the cause of this.

Hi @ciiay, thanks for the review.

I fixed this in the showcase repo with my 2nd PR. For me, it looks now like this:

image

> Another thing is about the software template card size. It misses some setting and the old issue will exist again. Here's [the comment](https://github.com/redhat-developer/red-hat-developer-hub-theme/commit/b157fa2ecdab98bcaad1252350b6aa71dcfd677f) I left for the cause of this issue in theme repo. The rest looks great to me. Thank you.

As we discussed, I restored your old PR and it looks now like this (with manually added more text):

image

**Review by ciiay — APPROVED** [review]
/lgtm

Tested on OCP cluster and it's working as expected 👏 Thank you!
image
image

**Pull request merged**
