### PR TITLE
chore(msg): update sign-in error message

### PR DESCRIPTION
**Pull request by kim-tsao**
## Description

Please explain the changes you made here.

Updating the existing message to include action items

## Which issue(s) does this PR fix

- Fixes #?
- https://issues.redhat.com/browse/RHIDP-4032

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

image

### CODE REVIEW

**Review by JessicaJHee — APPROVED** [review]
LGTM!

**Comment by kim-tsao** [comment]
@JessicaJHee I updated the msg based on feedback from @themr0c.  PTAL again, thanks!

**Pull request merged**
