### PR TITLE
refactor(homepage): migrate from internal dynamic-home-page to rhdh plugin

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Description

Use moved plugin from https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage/plugins/dynamic-home-page

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-5060

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by ciiay — APPROVED** [review]
/lgtm

I didn't try all the homepage setting variations, but I did verify that the dynamic-home-page plugin works from the new rhdh-plugins package using the PR image on a OCP v4.15 cluster.
image

image

**Comment by christoph-jerolimov** [comment]
We actual don't have tests for the home page and @ciiay verified that on a cluster. Time to merge...

/override ci/prow/e2e-tests
/cc @invincibleJai

**Comment by christoph-jerolimov** [comment]
Merging this now because home page has currently no e2e tests and we want get this in so that the configuration is aligned with other plugins!

Ticket to create e2e tests for homepage: RHIDP-5061

/override prow/e2e-tests

**Pull request merged**
