### PR TITLE
feat(dynamic-plugins): replace static MUI Icons library import with dynamic appIcons

### PR DESCRIPTION
**Pull request by tumido**
## Description

Instead of embedding all MUI4 icons into the bundle, we can depend in `app.getSystemIcon()` icon catalog. This PR allows users to extend it via dynamic plugins and therefore cleanup our bundle of unnecessary icons.

## Which issue(s) does this PR fix

~Depends on: https://github.com/janus-idp/backstage-plugins/pull/919~
Resolves: https://github.com/janus-idp/backstage-showcase/issues/725

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by tumido** [comment]
Hold for ocm plugin to release, we need to update it here. https://github.com/janus-idp/backstage-plugins/actions/runs/6801215513/job/18491731589

**Review by schultzp2020 — APPROVED** [review]
LGM

**Review by gashcrumb — APPROVED** [review]

**Comment by gashcrumb** [comment]
Of course after I approved I realized I was on the wrong branch.  Should this icon no longer be showing up with this change in place:

image

**Comment by gashcrumb** [comment]
Ah, sorry for the noise that's behaving as expected, I of course had it mis-configured locally :-)

**Review by kadel — APPROVED** [review]

**Pull request merged**
