### PR TITLE
update bulk-import version

### PR DESCRIPTION
**Pull request by debsmita1**
- updates bulk import plugins version
- updates topology plugin version
- updates rbac plugin version

### CODE REVIEW

**Comment by rm3l** [comment]
/hold

@subhashkhileri If you want to test this and validate the fixes, please feel free to do so. Otherwise, please remove the hold label.

**Comment by its-mitesh-kumar** [comment]
Verified Toplogy on cluster 
Screenshot 2024-09-11 at 2 12 32 PM

**Comment by debsmita1** [comment]
@its-mitesh-kumar  updated the topology plugin version to include the VM status icon changes

**Comment by divyanshiGupta** [comment]
Tested RBAC plugin and it is working fine.

https://github.com/user-attachments/assets/1ff92fdc-d3a3-44fb-9814-b1ebf6691afa


https://github.com/user-attachments/assets/38d12c6b-85a7-465d-990f-0dac73160787

**Comment by subhashkhileri** [comment]
Tested the reported bulk import UI issues

**Pull request merged**
