### PR TITLE
fix(rbac): added unit test for AdminPage

### PR DESCRIPTION
**Pull request by ciiay**
## Description

Add unit test for AdminPage merged in #989 

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [x] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
image

### CODE REVIEW

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Review by gashcrumb — APPROVED** [review]
Great!  :+1:

**Comment by nickboldt** [comment]
Snice https://github.com/janus-idp/backstage-showcase/pull/989 is cherrypicked to 1.1.x, evidently this should be too.

/cherry-pick 1.1.x

**Comment by nickboldt** [comment]
Cherrypick failed, see https://github.com/janus-idp/backstage-showcase/pull/1019 for manual PR + merge.

**Pull request merged**
