### PR TITLE
chore(github): add checkboxes to PR acceptance criteria

### PR DESCRIPTION
**Pull request by kadel**
## Description

adds checkboxes to PR acceptance criteria to make it the requirements more visible to review and PR author

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by schultzp2020 — APPROVED** [review]
LGTM

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by christophe-f** [comment]
I believe we had that in the past and no one was updating them and it was replaced to a list instead.

**Review by christophe-f — APPROVED** [review]
LGTM

**Pull request merged**
