### PR TITLE
Change import order for legacy dynamic plugin to load

### PR DESCRIPTION
**Pull request by masayag**
## Description

Please explain the changes you made here.

## Which issue(s) does this PR fix
Without this PR, an attempt to load the orchestrator-backend dynamic plugin fails with:
```
backend:start: 2023-11-20T10:38:41.167Z backstage info Adding plugin "orchestrator" to backend... 
backend:start: Backend failed to start up TypeError: Cannot read properties of undefined (reading 'fromConfig')
backend:start:     at createPlugin (/home/masayag/work/janus-idp/backstage-showcase/dynamic-plugins-root/orchestrator-backend/dist/index.cjs.js:30:51)
backend:start:     at addPlugin (webpack-internal:///./src/index.ts:118:39)
backend:start:     at main (webpack-internal:///./src/index.ts:252:23)
app:start: webpack compiled successfully
```

with this PR the plugin is loaded successfully:
```
backend:start: 2023-11-20T10:40:12.382Z backstage info Adding plugin "orchestrator" to backend... 
backend:start: 2023-11-20T10:40:12.385Z orchestrator warn No GitHub token found. Some features may not work as expected. type=plugin
backend:start: 2023-11-20T10:40:12.391Z orchestrator info Reloading workflows from Git type=plugin
backend:start: 2023-11-20T10:40:12.392Z orchestrator info Path /tmp/orchestrator/repository already exists. Skipping clone. type=plugin
backend:start: 2023-11-20T10:40:12.392Z orchestrator info Checking SonataFlow health at: http://localhost:8899/q/health type=plugin
backend:start: 2023-11-20T10:40:12.470Z orchestrator info SonataFlow is up and running type=plugin
backend:start: 2023-11-20T10:40:12.474Z backstage info Adding router "api" to backend... 
backend:start: 2023-11-20T10:40:12.475Z backstage info Adding router "healthcheck" to backend... 
backend:start: 2023-11-20T10:40:12.482Z backstage info Adding router "metrics" to backend... 
backend:start: 2023-11-20T10:40:12.494Z backstage info Adding router "app" to backend... 
backend:start: 2023-11-20T10:40:12.502Z backstage info Listening on :7007 
```

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
Used the following [script](https://gist.github.com/masayag/04ded7c75f8eb0d80da0a811c5488515#file-build-showcase-sh) to build orchestrator plugins and add them to showcase.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@christophe-f fyi

**Comment by davidfestal** [comment]
I don't see why the import order would fix the error here.
Fixing it this way worries me TBF.

cc @tumido

**Comment by tumido** [comment]
I have to fully agree with @davidfestal here.

1) What is the orchestrator dynamic backend plugin? How come this is the only plugin causing such issues? Would you kind to provide us with an example, a reproducer?

2) Please explain how this PR is fixing the issue. What is the mechanism? Because the symbol order in named imports doesn't matter. Never did. The whole file is always read and executed no matter which symbols you wish to import. That's simply how JavaScript works. You can't get a file partial with "just the firstly named symbol", then another partial with the "secondly named symbol". You don't read files like that...

I suspect a cache or hoisting issue on your end.

**Comment by masayag** [comment]
Thank you both for pointing out an issue with the plugin. So it appears on the plugin side, that the `HostDiscovery` was imported from the `@backstage/backend-common` instead of `@backstage/backend-app-api` which somehow reordering the import made it somehow work.
Fixing this issue on the plugin side. sorry for the noise.

**Pull request closed without merging**
