### PR TITLE
feat(ui): enable customization of static items in sidebar menu

### PR DESCRIPTION
**Pull request by ciiay**
## Description

Add dynamic plugin configuration for default navigation items.

## Which issue(s) does this PR fix

- For [RHIDP-3650](https://issues.redhat.com/browse/RHIDP-3650).

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [x] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
Configuration for testing:
```
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    default.main-menu-items:
      menuItems:
        default.list:
          title: References
          icon: bookmarks
        default.my-group:
          parent: default.list
        default.learning-path:
          parent: default.list
```

Screen recording:

https://github.com/user-attachments/assets/1dfcff83-8831-4458-b75c-db823e6f424e

<details>
<summary>Tested on OCP v4.15</summary>

https://github.com/user-attachments/assets/65529a1c-baf8-4c11-9dbf-a91b7d5123ca

</details>

### CODE REVIEW

**Comment by invincibleJai** [comment]
Verified the changes looks good 👍 

image

**Comment by invincibleJai** [comment]
@gashcrumb would be great if you can take a final look, thanks!

**Review by gashcrumb — APPROVED** [review]
:+1:

**Pull request merged**
