### PR TITLE
fix(e2e): [release-1.3] disable Tekton 

### PR DESCRIPTION
**Pull request by Omar-AlJaljuli**
## Description

Temporary measure to fix namespace termination issue

## Which issue(s) does this PR fix

https://issues.redhat.com/browse/RHIDP-4752

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by Omar-AlJaljuli** [comment]
@PatAKnight I believe these are the changes needed to fix the issue in the release-1.3

**Comment by PatAKnight** [comment]
Thank you for this! I see you also skipped the tests in the [main branch](https://github.com/janus-idp/backstage-showcase/blob/main/e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts#L13), is that not needed for this [branch](https://github.com/janus-idp/backstage-showcase/blob/release-1.3/e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts#L13)?

**Comment by Omar-AlJaljuli** [comment]
> Thank you for this! I see you also skipped the tests in the [main branch](https://github.com/janus-idp/backstage-showcase/blob/main/e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts#L13), is that not needed for this [branch](https://github.com/janus-idp/backstage-showcase/blob/release-1.3/e2e-tests/playwright/e2e/plugins/tekton/tekton.spec.ts#L13)?

I forgot to add the skip, I pushed the needed change :+1: . Thanks.

**Comment by Omar-AlJaljuli** [comment]
Recent merged PRs by @gustavolira make this redundant.

**Pull request closed without merging**
