### PR TITLE
feat(deps): update to backstage 1.27

### PR DESCRIPTION
**Pull request by schultzp2020**
## Description

Confirm plugin updates work:

- Techdocs
- GitLab Org

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-2334

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by Zaperex** [comment]
As mentioned in the [patch for the `plugin-app-backend` package](https://github.com/janus-idp/backstage-showcase/blob/b853f0ac59008497deed4c445d1804f14e25e05b/patches/%40backstage%2Bplugin-app-backend%2B0.3.65.patch#L13), we can remove the patch file for `@backstage/plugin-app-backend` since this PR upgrades the dependency to `0.3.67` which has the required changes.

**Comment by nickboldt** [comment]
/lgtm

other than the usual prow failures :this-is-fine:

**Review by nickboldt — COMMENTED** [review]
I like it but what do we think about the never-passing prow jobs? 

https://media.giphy.com/media/mx9fVEF08tyne/giphy.gif

(great, now that song is stuck in my head...)

**Pull request merged**
