### PR TITLE
[1.3.x] [e2e-tests] manual cherrypick for 1588

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Description

This is a manual cherrypick for #1588 targeting the 1.3.x branch.

Note: PR #1604 must be merged prior to this.

## Which issue(s) does this PR fix

https://issues.redhat.com/browse/RHIDP-1006

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by josephca** [comment]
@subhashkhileri fyi, I resolved the merge conflicts

**Comment by josephca** [comment]
> /hold until PR #1604 is merged.

#1604 is merged

**Review by nickboldt — APPROVED** [review]
didn't read carefully, just approving to encourage automation to merge this if the tests pass

**Comment by nickboldt** [comment]
tests failing @josephca  can you have a look?

**Comment by subhashkhileri** [comment]
temparaly switched to base 1.3.x just see the git hub issue is resolved or not. I have switched the gitapp for 1.3

**Review by zdrapela — APPROVED** [review]

**Pull request merged**
