### PR TITLE
fix(rbac): add more static plugins to RBAC list

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
## Description

Add more static plugins to the RBAC list. These plugins are required to retrieve plugin permissions and condition rules, providing them to the frontend via REST.

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by davidfestal — APPROVED** [review]

**Comment by invincibleJai** [comment]
LGTM

**Review by PatAKnight — APPROVED** [review]
LGTM

**Comment by AndrienkoAleksandr** [comment]
@kadel Sorry, I don't have rights to merge.

**Comment by PatAKnight** [comment]
Looks like the CI is failing because you are missing a changeset. Can you please add one?

**Pull request merged**
