### PR TITLE
Fix app-config.yaml

### PR DESCRIPTION
**Pull request by 04kash**
## Description

Following [this change](https://github.com/janus-idp/backstage-showcase/pull/1271) of replacing the start command by `turbo run build --filter=app && turbo run start --filter=backend`, this PR updates `app.baseUrl`to `http://localhost:7007` in `app-config.yaml` as the frontend app is now served automatically as part of backend.

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by Zaperex — APPROVED** [review]
/lgtm

**Comment by Zaperex** [comment]
@04kash on second thought, can you also update the `getting-started.md` docs to indicate this new change. Also it would be nice if we had something like a `dev` command that starts up backstage with the old behavior (`turbo run start --filter=backend --filter=app`) since the new behavior no longer allows for hot reloads of the frontend.

**Comment by Zaperex** [comment]
Updated PR to include the old behavior as the new behavior does not allow for hot reloading of the frontend. Also added additional docs about the new ways to start the showcase, as well as the caveats.

**Review by kim-tsao — APPROVED** [review]

**Pull request merged**
