### PR TITLE
chore: add patches for scaffolder audit logging with scaffolder permissions

### PR DESCRIPTION
**Pull request by Zaperex**
## Description

Adding the [`scaffolder audit logging changes`](https://github.com/redhat-developer/backstage/pull/1) via a patch using `patch-package`

This will also include cherry picked changes for the scaffolder permissions since the audit logging changes are built on the `v1.26.5` branch, while the scaffolder permissions are released in `v1.28.0-next.1`

Relates to https://github.com/janus-idp/backstage-showcase/pull/1265

## Which issue(s) does this PR fix

Relates to [RHIDP-2324](https://issues.redhat.com/browse/RHIDP-2324)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
If running on Node 20, start with:
```bash
NODE_OPTIONS=--no-node-snapshot
```

Verifying audit logging
  - Use the scaffolder (frontend or backend) (make sure you are logged in with a backstage identity or else `actorId` will be `null`)
  - Observe audit logs be outputted for router endpoint access, task creation, cancellation, execution, etc.

The new permissions add the following new behaviours:
- Verify that new permissions are available via `<BACKEND_URL>/api/scaffolder/.well-known/backstage/permissions/metadata`
- `scaffolder.task.read`: prevents reading of tasks, task events/eventstreams
  - Test with the `GET /v2/tasks`, `GET /v2/tasks/:taskId`, `GET /v2/tasks/:taskId/events` and `GET /v2/tasks/:taskId/eventstream` endpoints
  - Test with the UI: View log stream, list tasks
- `scaffolder.task.create`: prevents creation of scaffolder tasks (can't trigger a software template)
  - Test with the `POST /v2/tasks` endpoint and try launching a software template via the UI (catalog entity about page, and Create page should both have their buttons disabled)
- `scaffolder.task.cancel`: prevents cancellation of scaffolder tasks
  - Test with the `POST /v2/tasks/:taskId/cancel` endpoint and try cancelling a running task in the UI (cancel button should be disabled)

### CODE REVIEW

**Comment by Zaperex** [comment]
Yet again, patch fails after doing a `rm -rf node_modules`. Tried debugging by running `yarn postinstall --partial` to get an error log:
[patch-package-errors.md](https://github.com/janus-idp/backstage-showcase/files/15470301/patch-package-errors.md)

**Comment by Zaperex** [comment]
For some reason the error log I posted above seemed to complain about the `plugin-app-backend` patch despite it working when I run `yarn postinstall`:
```bash
yarn postinstall
yarn run v1.22.19
$ patch-package
patch-package 8.0.0
Applying patches...
@backstage/plugin-app-backend@0.3.65 ✔
@backstage/plugin-scaffolder-node@0.4.3 ✔

**ERROR** Failed to apply patch for package @backstage/plugin-scaffolder-backend at path
  
    node_modules/@backstage/plugin-scaffolder-backend

  This error was caused because patch-package cannot apply the following patch file:

    patches/@backstage+plugin-scaffolder-backend+1.22.5.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package @backstage/plugin-scaffolder-backend
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
    

---
patch-package finished with 1 error(s).
```

**Comment by Zaperex** [comment]
Cherry picked the scaffolder permission changes into the existing audit log changes.

Created a script to try to automate as much of the patching process as possible: https://gist.github.com/Zaperex/5cf97c464bb0459e97ad8ebe9ad397d2

Frontend plugins would require some manual modifications as I haven't figured out a reliable way to map the file name changes when there are multiple (ex: catalog plugin had multiple `index-<hash>` and `alpha-<hash>` files generated from `yarn build` in the `dist/esm` directory).

Currently the audit logger patch does not pull in the `audit-log-node` common package since it has not been published yet. It is currently added in-line.

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
