### PR TITLE
chore(rbac): update rbac rbac-backend and rbac-common plugins versions

### PR DESCRIPTION
**Pull request by divyanshiGupta**
## Description

This is a manual cherry-pick of https://github.com/janus-idp/backstage-showcase/pull/1415

Screenshot 2024-07-18 at 3 33 42 PM
Screenshot 2024-07-18 at 3 36 11 PM

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-3038

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]

**Comment by debsmita1** [comment]
verified the changes
Screenshot 2024-07-18 at 6 59 05 PM

/lgtm

**Comment by nickboldt** [comment]
merging despite failing tests cuz the show must go one and @debsmita1 already verified

**Pull request merged**
