### PR TITLE
Add test logs as a PR comment

### PR DESCRIPTION
**Pull request by josephca**
## Description

Add a PR commenter bot to add a link to the PR test log as a PR comment.

## Which issue(s) does this PR fix

- Fixes [[Test automation] Integrate PRs with CI infra to add links within PRs to test logs](https://issues.redhat.com/browse/RHIDP-436)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by nickboldt** [comment]
looks good; only negative commment is that the comment says "finished with errors" but the test shows a checkmark for a successfully completed pipeline:

image

**Comment by josephca** [comment]
> looks good; only negative is that the comment on teh PR says "finished with errors" but the test shows a checkmark for a successfully completed pipeline:
> 
> image
> 
> Might be nice (if possible) to make the "fnished with errors" bold or red or just more obviously wrong. :D

Thanks @nickboldt. Yes, as I mentioned in the demo, this issue that you mentioned is a known issue and already handled with this PR. BTW, I didn't expect any review as it's a draft PR. :)

**Comment by nickboldt** [comment]
> I didn't expect any review as it's a draft

Yeah, I know you mentioned this was a known concern. I just wanted to write it down to avoid it getting lost.

**Comment by josephca** [comment]
> looks good; only negative is that the comment on teh PR says "finished with errors" but the test shows a checkmark for a successfully completed pipeline:
> 
> image
> 
> Might be nice (if possible) to make the "fnished with errors" bold or red or just more obviously wrong. :D

Your wish came true. :) I added code to make the test result displayed in **boldface**.

**Comment by josephca** [comment]
Ready to be merged.

**Review by schultzp2020 — APPROVED** [review]
LGTM

**Pull request merged**
