### PR TITLE
bump base images to use Node.js 20

### PR DESCRIPTION
**Pull request by BethGriggs**
## Description

This is an attempt to test if a combination of https://github.com/janus-idp/backstage-showcase/pull/1043 and updating the Dockerfiles to use the Node.js 20 images passes CI 🤞🏻 

## Which issue(s) does this PR fix

- Fixes https://github.com/janus-idp/backstage-showcase/issues/880

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [x] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by davidfestal** [comment]
@BethGriggs Do you think you could rebase the PR, and I would review it ?

**Comment by davidfestal** [comment]
> Any guidance on how to debug this workflow?
> 
> > Tests on OCP/PR Test — This pipeline stage has failed [Details](https://cloud.ibm.com/devops/pipelines/a8b24d6b-7878-4b9c-b48a-bab3ca9a1f8f/42ebfc0d-4644-4945-80ea-5f5a52e0bbd7/a938649c-d42a-4469-8865-45726b9b7e55?env_id=ibm:yp:eu-de)
> 
> It seems to bring me to an IBM login page that I am not sure if I have am supposed to have an account for?

cc @josephca

**Comment by nickboldt** [comment]
other than the failing prow stuff, I'm good with this. But let's maybe do it on Monday instead of Friday afternoon :D 

I would want to see a +1 from @josephca about switching to node20 and how that might impact test suites.

**Comment by nickboldt** [comment]
Failing prow tests:

image

```
Run multi-stage test e2e-tests - e2e-tests-janus-idp-backstage-showcase container test expand_less	5m11s
{  )
Backstage is up and running!
######## BASE URL ########
https://rhdh-backstage-showcase-ci.rhdh-pr-os-a9805650830b22c3aee243e51d79565d-0000.us-east.containers.appdomain.cloud
Display pods for verification...
NAME                                                     READY   STATUS      RESTARTS   AGE
hello-world-pipeline-run-echo-bye-pod                    0/1     Completed   0          3m42s
hello-world-pipeline-run-echo-hello-world-pod            0/1     Completed   0          3m42s
rhdh-backstage-55d88b54d-2dnql                           1/1     Running     0          3m33s
rhdh-postgresql-0                                        1/1     Running     0          3m33s
test-app-5987847886-8wkfz                                1/1     Running     0          4m11s
test-app-5987847886-lcbvv                                1/1     Running     0          4m11s
test-backstage-customization-provider-1-build            0/1     Completed   0          4m9s
test-backstage-customization-provider-7f694cd945-vf2hv   1/1     Running     0          2m54s
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ playwright install
Done in 6.78s.
yarn run v1.22.19
$ /tmp/backstage-showcase/e2e-tests/node_modules/.bin/playwright install
Done in 0.70s.
Using PR container image: next
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
yarn run v1.22.19
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cp: cannot stat '/tmp/backstage-showcase/e2e-tests/test-results/*': No such file or directory
Cleaning up before exiting
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-04-26T14:36:32Z"}
error: failed to execute wrapped command: exit status 1
}
```

and

```
Run multi-stage test test phase expand_less	6m14s
{  "e2e-tests" pod "e2e-tests-janus-idp-backstage-showcase" failed: could not watch pod: the pod ci-op-q8vvtct8/e2e-tests-janus-idp-backstage-showcase failed after 6m13s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
)
Backstage is up and running!
######## BASE URL ########
https://rhdh-backstage-showcase-ci.rhdh-pr-os-a9805650830b22c3aee243e51d79565d-0000.us-east.containers.appdomain.cloud
Display pods for verification...
NAME                                                     READY   STATUS      RESTARTS   AGE
hello-world-pipeline-run-echo-bye-pod                    0/1     Completed   0          3m42s
hello-world-pipeline-run-echo-hello-world-pod            0/1     Completed   0          3m42s
rhdh-backstage-55d88b54d-2dnql                           1/1     Running     0          3m33s
rhdh-postgresql-0                                        1/1     Running     0          3m33s
test-app-5987847886-8wkfz                                1/1     Running     0          4m11s
test-app-5987847886-lcbvv                                1/1     Running     0          4m11s
test-backstage-customization-provider-1-build            0/1     Completed   0          4m9s
test-backstage-customization-provider-7f694cd945-vf2hv   1/1     Running     0          2m54s
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ playwright install
Done in 6.78s.
yarn run v1.22.19
$ /tmp/backstage-showcase/e2e-tests/node_modules/.bin/playwright install
Done in 0.70s.
Using PR container image: next
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
yarn run v1.22.19
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cp: cannot stat '/tmp/backstage-showcase/e2e-tests/test-results/*': No such file or directory
Cleaning up before exiting
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-04-26T14:36:32Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/janus-idp-backstage-showcase
Link to job on registry info site: https://steps.ci.openshift.org/job?org=janus-idp&repo=backstage-showcase&branch=main&test=e2e-tests}
```

**Comment by josephca** [comment]
> other than the failing prow stuff, I'm good with this. But let's maybe do it on Monday instead of Friday afternoon :D
> 
> I would want to see a +1 from @josephca about switching to node20 and how that might impact test suites.

@nickboldt It shouldn't impact the test as the testing container is based on the playwright image with node20.

**Comment by nickboldt** [comment]
showcase next build succeeded 34 mins ago, pushed to https://quay.io/repository/janus-idp/backstage-showcase?tab=tags (search for next tag)

downstream was already running against an older commit, have forced it to update to see what happens... https://gitlab.cee.redhat.com/rhidp/rhdh/-/pipelines/8072244a

**Comment by nickboldt** [comment]
Build is good in https://gitlab.cee.redhat.com/rhidp/rhdh/-/jobs/21723839 => https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=60856898 =>  registry-proxy.engineering.redhat.com/rh-osbs/rhdh-rhdh-hub-rhel9:1.2-58 :tada:

**Pull request merged**
