### PR TITLE
chore(deps): update RHDH theme

### PR DESCRIPTION
**Pull request by jerolimov**
## Description

Update RHDH theme to include:

- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/8
- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/10
- https://github.com/redhat-developer/red-hat-developer-hub-theme/pull/11

## Which issue(s) does this PR fix

- 8 fixes https://issues.redhat.com/browse/RHIDP-2289
- 10 fixes https://issues.redhat.com/browse/RHIDP-2290
- 11 fixes https://issues.redhat.com/browse/RHIDP-2300

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by karthikjeeyar — COMMENTED** [review]
Changes looks good to me

/lgtm

**Comment by ciiay** [comment]
I know it's already merged, but I finally got the local image work to test it out, here's the screen recording.

https://github.com/janus-idp/backstage-showcase/assets/26255262/59901e22-7433-4b6e-9e9e-c9a92ab87814

**Review by ciiay — COMMENTED** [review]
The image of this PR works perfectly on OCP cluster to address the issues it should resolved.

**Pull request merged**
