### PR TITLE
refactor: modularize OpenShift CI script for better maintainability

### PR DESCRIPTION
**Pull request by gustavolira**
Modularized the OpenShift CI script by separating main functionalities into individual files. This change improves the maintainability and readability of the scripts by isolating specific tasks, such as handling AKS/GKE deployments and finalizers.

## Description

Please explain the changes you made here.

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by zdrapela — CHANGES_REQUESTED** [review]
Hi @gustavolira, thank you for that, this is definitely needed! I have a couple of thoughts about that though.

1. There are already separate files for AKS, GKE (and OSD) located here: https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/pipelines//cluster 
Please make sure to take them into account and incorporate them.
2. We have the `install_oc` and `install_helm` functions there, but they are redundant, since we are already installing both int he https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/images/Dockerfile#L37. I vote for deleting them.
3. Now we use only single `openshift-ci-tests.sh` file to run the jobs and then we differentiate it based on the job name. I think we better split it and use the `openshift-ci-tests.sh` for OCP tests and https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/pipelines/kubernetes-tests.sh for Kubernetes tests (GKE and AKS). (I would delete this file's content first, as it is not used anymore and start from a blank file.)
To do that, we can edit https://github.com/openshift/release/blob/4d24aecb5f0cb787a9ec0e3e6d1744f234c3e184/ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/janus-idp-backstage-showcase-helm-aks-nightly-commands.sh#L19 and https://github.com/openshift/release/blob/4d24aecb5f0cb787a9ec0e3e6d1744f234c3e184/ci-operator/step-registry/janus-idp/backstage-showcase/helm-gke-nightly/janus-idp-backstage-showcase-helm-gke-nightly-commands.sh#L19 
That way we can avoid some more `if`s and `case` switches.

I offer my assistance with AKS and GKE. 

If you want to test that these changes are not breaking them, you can follow[ this doc ](https://docs.google.com/document/d/18kA2mtl25GFp0Cp4n-u1lBijlGtFQkD-OQZLM6eb4aw/edit) and also set `JOB_NAME=periodic-aks` or `JOB_NAME=periodic-gke` respectively.

**Comment by gustavolira** [comment]
> Hi @gustavolira, thank you for that, this is definitely needed! I have a couple of thoughts about that though.
> 
> 1. There are already separate files with functions for AKS, GKE (and OSD) located here: https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/pipelines//cluster
>    Please make sure to take them into account and incorporate them.
> 2. We have the `install_oc` and `install_helm` functions there (in `openshift-ci-tests.sh` or `utils.sh`), but they are redundant, since we are already installing both in the https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/images/Dockerfile#L37. I vote for deleting them.
> 3. Now we use only a single `openshift-ci-tests.sh` file to run the jobs and then we differentiate it based on the job name. I think we better split it and use the `openshift-ci-tests.sh` for OCP tests and https://github.com/janus-idp/backstage-showcase/blob/main/.ibm/pipelines/kubernetes-tests.sh for Kubernetes tests (GKE and AKS). (I would delete the  `kubernetes-tests.sh`s content first, as it is not used anymore, and start from scratch.)
>    To do that, we can edit https://github.com/openshift/release/blob/4d24aecb5f0cb787a9ec0e3e6d1744f234c3e184/ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/janus-idp-backstage-showcase-helm-aks-nightly-commands.sh#L19 and https://github.com/openshift/release/blob/4d24aecb5f0cb787a9ec0e3e6d1744f234c3e184/ci-operator/step-registry/janus-idp/backstage-showcase/helm-gke-nightly/janus-idp-backstage-showcase-helm-gke-nightly-commands.sh#L19
>    That way we can avoid some more `if`s and `case` switches.
> 
> I offer my assistance with AKS and GKE.
> 
> If you want to test that these changes are not breaking AKS and GKE yourself, you can follow[ this doc ](https://docs.google.com/document/d/18kA2mtl25GFp0Cp4n-u1lBijlGtFQkD-OQZLM6eb4aw/edit) and also set `JOB_NAME=periodic-aks` or `JOB_NAME=periodic-gke` respectively.

Hi @zdrapela thank you very much for your attention here! 
1. ACK
2. thank you very much for the heads up, I will delete them
3. Can we address this after completing the refactoring? I have limited knowledge of those files, and I want to avoid making this process more complex. Delaying the merge will likely result in numerous Git conflicts, so I’d prefer to merge it as soon as possible to minimize that risk.

**Comment by zdrapela** [comment]
> Hi @zdrapela thank you very much for your attention here!
> 
> 1. ACK
> 2. thank you very much for the heads up, I will delete them
> 3. Can we address this after completing the refactoring? I have limited knowledge of those files, and I want to avoid making this process more complex. Delaying the merge will likely result in numerous Git conflicts, so I’d prefer to merge it as soon as possible to minimize that risk.

3. Yes, we can do that after this. We can do that easily when the `openshift-ci-tests.sh` is small.

**Pull request closed without merging**
