### PR TITLE
chore(deps): update dynamic home page from mui v4 to v5

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Description

Updates the dynamic home page cards from MUI v4 to v5. It replaces #1667 with the necessary code changes.

## Which issue(s) does this PR fix

- Fixes [RHIDP-4309](https://issues.redhat.com/browse/RHIDP-4309)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Comment by christoph-jerolimov** [comment]
Tests pass once, and then they fail in retest.

/override ci/prow/e2e-tests

**Pull request merged**
