### PR TITLE
[Test automation] Configure and verify GitHub integration with Org data fetching

### PR DESCRIPTION
**Pull request by Omar-AlJaljuli**
## Description
Configured the environment to integrate the Janus-qe organization into the catalog. Created an automated test file that checks if the integration works. https://issues.redhat.com/browse/RHIDP-753.

Configuration followed from: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html-single/getting_started_with_red_hat_developer_hub/index#proc-add-source-control-rhdh-catalog_rhdh-getting-started

## Which issue(s) does this PR fix

[RHIDP-753](https://issues.redhat.com/browse/RHIDP-753)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by josephca** [comment]
@subhashkhileri can you provide a review? Thanks!

**Comment by subhashkhileri** [comment]
@josephca @Omar-AlJaljuli  This test is already covered in github happy path : https://github.com/janus-idp/backstage-showcase/blob/main/e2e-tests/playwright/e2e/github-happy-path.spec.ts#L46 

you would like to enhance or update the existing test or remove from old and keep it like this?

**Comment by Omar-AlJaljuli** [comment]
> @josephca @Omar-AlJaljuli This test is already covered in github happy path : https://github.com/janus-idp/backstage-showcase/blob/main/e2e-tests/playwright/e2e/github-happy-path.spec.ts#L46
> 
> you would like to enhance or update the existing test or remove from old and keep it like this?

@subhashkhileri I believe the test you're talking about in github happy path tests the fetching of components from repos that have something like a catalog-info.yaml file [Documentation for whats being tested in GH happy path](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.1/html-single/getting_started_with_red_hat_developer_hub/index#enabling-github-discovery-in-red-hat-developer-hub) , but this tests if the organization integrated with it is visible [Documentation for whats being tested by this PR](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.1/html-single/getting_started_with_red_hat_developer_hub/index#enabling-github-organization-member-discovery-in-red-hat-developer-hub)

**Comment by josephca** [comment]
> > @josephca @Omar-AlJaljuli This test is already covered in github happy path : https://github.com/janus-idp/backstage-showcase/blob/main/e2e-tests/playwright/e2e/github-happy-path.spec.ts#L46
> > you would like to enhance or update the existing test or remove from old and keep it like this?
> 
> @subhashkhileri I believe the test you're talking about (in github happy path) tests the fetching of components from repos that have something like a catalog-info.yaml file [Documentation for whats being tested in GH happy path](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.1/html-single/getting_started_with_red_hat_developer_hub/index#enabling-github-discovery-in-red-hat-developer-hub). This PR tests if the organization that was integrated with is visible with the right config [Documentation for whats being tested by this PR](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.1/html-single/getting_started_with_red_hat_developer_hub/index#enabling-github-organization-member-discovery-in-red-hat-developer-hub)

@subhashkhileri @Omar-AlJaljuli I think Omar is right. For example, the 'github happy path' is getting the group from https://github.com/janus-idp/backstage-showcase/blob/ef76d0e31b824f527777a811c013f9dd3e93f996/catalog-entities/groups/janus-authors.yaml#L6 - not from the 'githubOrg'.

**Pull request merged**
