### PR TITLE
RHIDP-1149: Enable Auto Logout feature by default, provide configuration options and documentation

### LINKED ISSUE #664: Add the auto logout feature
### What needs to be done?

1. Make sure the auto logout feature is available in showcase
https://backstage.io/docs/auth/autologout/

2. The feature should be disable by default
3. Update the documentation with how to enable it and configure it

### PR DESCRIPTION
**Pull request by coreydaley**
## Description

 - Modified packages/app/src/components/AppBase/AppBase.tsx to include the AutoLogout component, enables by default and includes the [defaults](https://backstage.io/docs/auth/autologout/) recommended by Backstage.
 - Modified app-config.yaml to include options to modify the Auto Logout feature using environment variables.
 - Updated showcase-docs/getting-started.md to include information about `Secure by Default`, having the Auto Logout feature enabled by default, and how to modify that configuration.

## Which issue(s) does this PR fix

- Fixes #664 

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
The Auto Logout feature does not work using the `Guest` login and was tested using the Github login feature.

### CODE REVIEW

**Comment by gashcrumb** [comment]
I took a moment to try this locally but when running `yarn start` I see this error; maybe this dependency comes from the autologout component and just needs to be added to the `package.json`.

Screenshot from 2024-02-08 11-09-49

**Comment by gashcrumb** [comment]
> I took a moment to try this locally but when running `yarn start` I see this error; maybe this dependency comes from the autologout component and just needs to be added to the `package.json`.
> 

Never mind this, gave it another try and didn't have this error again.  Autologout feature worked for me too, great!

**Review by gashcrumb — APPROVED** [review]
If we're keeping changelogs this PR will need one, but other than that looks good to me.

**Comment by coreydaley** [comment]
/hold
According to https://github.com/backstage/backstage/issues/22692#issuecomment-1934834380, the AutoLogout feature may introduce a false sense of security and not actually completely log the user out. Further investigation may be needed, or this may not be worth enabling.

**Comment by nickboldt** [comment]
6 months later this is still unmerged, so I'm going to close it for now. @coreydaley if that's an error, LMK and/or please reopen it.

**Pull request closed without merging**
