### PR TITLE
feat(header): verify appbar integration spike

### PR DESCRIPTION
**Pull request by ciiay**
## Description

For [RHIDP-5247](https://issues.redhat.com/browse/RHIDP-5247). Just for review/spike, **DO NOT MERGE**

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

Simply run `yarn install` and `yarn dev` to start showcase.

https://github.com/user-attachments/assets/9059f8cb-5c2c-4ed3-95e9-0a91c0b8877f

### CODE REVIEW

**Comment by ShiranHi** [comment]
@ciiay looks great! 
Three questions: 
1. Could we make the width of the Settings menu smaller? It feels a bit too wide to me
2. I'm not sure if this is covered in this ticket, but once we have the Create, Notifications, and Settings buttons in the header, we can remove them from the side navigation. The purpose of having a global header is to minimize the clutter in the side navigation.
3. Could you please show the search behavior?

**Comment by ciiay** [comment]
Hi @ShiranHi , thanks for the review.

> 1. Could we make the width of the Settings menu smaller? It feels a bit too wide to me

In order to compare easily, I put the current width and Figma width as following. I have updated it to `188px`
1. min-width: 200px
image

2. min-width: 188px, as showed in Figma
image


> 2. I'm not sure if this is covered in this ticket, but once we have the Create, Notifications, and Settings buttons in the header, we can remove them from the side navigation. The purpose of having a global header is to minimize the clutter in the side navigation.

Thanks for clarifying the design change on sidebar when global-header is enabled. This PR is to demo the integration of AppBar with showcase, not much actual logic included. We will add this requirement in other stories to remove duplicated items from sidebar navigation.

> 3. Could you please show the search behavior?

The search behavior hasn't been implemented in this PR yet. I wanted to confirm with you. Does this search bar work same way as the current one in the sidebar? Or it will have a different behavior?

Here's an updated screenshot after addressing your review comment. Let me know if further changes are needed.
image

**Comment by ShiranHi** [comment]
> In order to compare easily, I put the current width and Figma width as following. I have updated it to `188px`

Let's change it to be 160ox please, so it will follow the Material Design guidelines. 


> We will add this requirement in other stories to remove duplicated items from sidebar navigation.

Thank you!


> Does this search bar work same way as the current one in the sidebar? Or it will have a different behavior?

Can we allow users to type in the search field and display some results in real-time ([Figma](https://www.figma.com/design/GeVb7rc390TkxeQNnJIcBD/RHDH-Theme-(pages)?node-id=664-256&t=wywYDh7VwQpUtkWa-1)) before navigating them to [the full page](https://demo.backstage.io/search?query=temp)?

**Comment by ciiay** [comment]
> Let's change it to be 160ox please, so it will follow the Material Design guidelines.

👌 Will do so. This is a spike PR, the real change that goes into the plugin will be on [this PR](https://github.com/redhat-developer/rhdh-plugins/pull/203) against rhdh-plugins repository. Let's confirm the appearance again there. Thank you 🌷 

> Can we allow users to type in the search field and display some results in real-time ([Figma](https://www.figma.com/design/GeVb7rc390TkxeQNnJIcBD/RHDH-Theme-(pages)?node-id=664-256&t=wywYDh7VwQpUtkWa-1)) before navigating them to [the full page](https://demo.backstage.io/search?query=temp)?

I have created [RHIDP-5365](https://issues.redhat.com/browse/RHIDP-5365) to implement this new searchBar.

> One more thing I noticed - please ensure that the PF colors are used for text, icons and borders.

This will be addressed in [RHIDP-5364](https://issues.redhat.com/browse/RHIDP-5364).

Also created [RHIDP-5363](https://issues.redhat.com/browse/RHIDP-5363) to hide duplicated items from sidebar menu.

Let me know if there's any inaccurate description in my tickets and I will update it. 

@christoph-jerolimov It would be great if you can take a look too 📖  Let me know what do you think or what do I need to update.

Thank you both ✨ 😃

**Comment by christoph-jerolimov** [comment]
Hi, thanks @ciiay and @ShiranHi 

I think that was a great spike that everything is working an Shirans feedback was also worthful.

Also the 2 new stories is a perfect result of that spike. From my side everything looks good and we can close this PR and the ticket and to another review when we finished the first version of the plugin. :)

**Comment by ciiay** [comment]
Closing this PR as all feedback has been received and new stories got created to reflect the feedback.

**Pull request closed without merging**
