### PR TITLE
chore(ci): remove caching from docker builds

### PR DESCRIPTION
**Pull request by kadel**
## Description

GH Action for building the image started failing on full cache.
This is creating a lot of problems as our e2e tests depend on this image.

We probably need caching here, but till we figure out how to make it more stable, we have to remove it. It is batter to have it slower and stable than broken.

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by schultzp2020 — APPROVED** [review]
/lgtm
/approve

**Comment by kadel** [comment]
not waiting for image as it will fail anyway
/override "Docker Build / PR Docker Build (pull_request_target)"

**Pull request merged**
