### PR TITLE
chore(deps): upgrade to Backstage 1.17.5

### PR DESCRIPTION
**Pull request by kadel**
## Description

fixes issues that caused the following warning when starting showcase 

```
app:start: ⚠️   Some of the following packages may be outdated or have duplicate installations:
app:start:
app:start:           @backstage/plugin-catalog-backend, @backstage/plugin-kubernetes, @backstage/plugin-scaffolder-backend
app:start:
app:start: ⚠️   This can be resolved using the following command:
app:start:
app:start:           yarn backstage-cli versions:check --fix
app:start:
```
## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by schultzp2020** [comment]
@kadel Can you change this PR to updating backstage to `1.17.5`? For more [info](https://github.com/janus-idp/backstage-showcase/blob/main/CONTRIBUTING.md#updating-backstage-dependencies).

**Comment by kadel** [comment]
> @kadel Can you change this PR to updating backstage to `1.17.5`? For more [info](https://github.com/janus-idp/backstage-showcase/blob/main/CONTRIBUTING.md#updating-backstage-dependencies).

@schultzp2020 upgraded

**Review by schultzp2020 — CHANGES_REQUESTED** [review]
@kadel please update `backstage.json` as well.

**Comment by kadel** [comment]
> @kadel please update `backstage.json` as well.

oh, good catch, not sure how it got skipped.

**Review by schultzp2020 — APPROVED** [review]
LGTM - @kadel for some reason the backstage CLI does not update `backstage.json` :(

**Review by christophe-f — APPROVED** [review]
LGTM

**Pull request merged**
