### PR TITLE
fix: accomodate the move of `resolvePackagePath` from `backend-common ` to `backend-plugin-api`.

### PR DESCRIPTION
**Pull request by davidfestal**
## Description

Commit https://github.com/backstage/backstage/commit/d229dc49adbb3059153e14cf312a4889c8a4c66e on upstream backstage has moved the `resolvePackagePath` function from the `backend-common` package to the `backend-plugin-api` package.
We have to accommodate this move in the Backend Dynamic Plugins `CommonJSLoader`  implementation in the showcase. 

## Which issue(s) does this PR fix

No issue, but required to avoid future breakages.

related to https://issues.redhat.com/browse/RHIDP-3844

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by davidfestal** [comment]
I guess it would be a good thing to include this change in the 1.3.

cc @nickboldt

**Comment by nickboldt** [comment]
Unless it's a blocker, I would prefer to not add more changes to 1.3 at this point. Feature freeze was 3 weeks ago and code freeze was nominally yesterday. Is there an existing JIRA for this change? 

Also welcome back @davidfestal ! <3

**Comment by gashcrumb** [comment]
> Unless it's a blocker, I would prefer to not add more changes to 1.3 at this point. Feature freeze was 3 weeks ago and code freeze was nominally yesterday. Is there an existing JIRA for this change?

This will be a blocker, I just talked with a customer that hit this yesterday.

**Comment by gashcrumb** [comment]
Here's the relevant Jira -> https://issues.redhat.com/browse/RHIDP-3844

**Review by kadel — APPROVED** [review]

**Pull request merged**
