### PR TITLE
RHIDP-4544: fix(ui): hide menu items with no title in sidebar nav (#1690)

### PR DESCRIPTION
**Pull request by mareklibra**
Backport of https://github.com/janus-idp/backstage-showcase/pull/1690 to `release-1.3`

### CODE REVIEW

**Comment by mareklibra** [comment]
**Before:**
Screenshot from 2024-10-17 10-48-29


**After:**
Screenshot from 2024-10-17 10-49-28

**Review by jerolimov — APPROVED** [review]
This is a valid change!

/lgtm

**Pull request merged**
