### PR TITLE
chore(deps): bump bulk-import-backend-plugin to 1.5.3

### PR DESCRIPTION
**Pull request by rm3l**
## Description

Pulls in the fix from https://github.com/janus-idp/backstage-plugins/pull/2178

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-4021

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by rm3l** [comment]
FYI, this will be cherry-picked to 1.3.x via https://github.com/janus-idp/backstage-showcase/pull/1627/files

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Pull request merged**
