### PR TITLE
Updated how OAuth headers are processed

### PR DESCRIPTION
**Pull request by sabre1041**
## Description

Ability to define the HTTP header containing the username for the OAuth 2 Proxy Provider

Implements a fallback strategy

1. Environment variable defined by the value of `OAUTH_USER_HEADER`
2. `x-forwarded-preferred-username` HTTP Header (Primary use case: with Keycloak/RHSSO/RHBK)
3. `x-forwarded-user` (Primary use case: OpenShift)

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [x] Unit Tests are updated and passing
- [x] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

Make use of a variety of OAuth Providers:

1. Configure OpenShift OAuth based on instructions [here](https://janus-idp.io/blog/2023/02/20/using-openshift-authentication-to-secure-access-to-backstage)
2. Configure Keycloak based on instructions [here](https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage)
3. Specify the `OAUTH_USER_HEADER` with a desired header to utilize. You can specify any of the values that are natively provided by the two options previously mentioned

Within the documentation, ignore any details related to customizing the backstage image as the necessary configurations are implemented here

### CODE REVIEW

**Comment by kadel** [comment]
@sabre1041 Could you please add documentation for this? I know that he current state of the documentation is horrible, I am concerned that if we don't document this somewhere, we may forget that this option exists.

You could, for example, start a new file named `configuration.md` in the `showcase-docs` directory, we can later expand it with other options

**Comment by sabre1041** [comment]
Since there is no documentation.  What about instead starting a new issue that we can build out what we would want in the docs?

This would allow us to capture the material that should be included

**Comment by kadel** [comment]
> Since there is no documentation. What about instead starting a new issue that we can build out what we would want in the docs?
> 
> This would allow us to capture the material that should be included

This is precisely what got us to the point where we are now (zero documentation for most of the 
 things).
We need to make a habit of documenting things from the start. Yes, it sucks to write docs, but otherwise we will never get out of the mess we are in now)

**Comment by sabre1041** [comment]
> > Since there is no documentation. What about instead starting a new issue that we can build out what we would want in the docs?
> > This would allow us to capture the material that should be included
> 
> This is precisely what got us to the point where we are now (zero documentation for most of the things). We need to make a habit of documenting things from the start. Yes, it sucks to write docs, but otherwise we will never get out of the mess we are in now)

Can there be a baseline example to build off of?

**Comment by sabre1041** [comment]
> > > Since there is no documentation. What about instead starting a new issue that we can build out what we would want in the docs?
> > > This would allow us to capture the material that should be included
> > 
> > 
> > This is precisely what got us to the point where we are now (zero documentation for most of the things). We need to make a habit of documenting things from the start. Yes, it sucks to write docs, but otherwise we will never get out of the mess we are in now)
> 
> Can there be a baseline example to build off of?

any update?

**Comment by sabre1041** [comment]
> @sabre1041
> 
> It can be as simple as this
> 
> ```
> # showcase-docs/configuration-env-variables.md
> 
> 
> - `OAUTH_USER_HEADER` - HTTP header containing the username for the OAuth 2 Proxy Provider. If not set, it tries `x-forwarded-preferred-username` and `x-forwarded-user`
> ```

Done

**Review by kadel — APPROVED** [review]

**Comment by kadel** [comment]
test are unstable QE is working on fix

/override "Tests on OCP/PR Test"

**Pull request merged**
