### PR TITLE
update icons on the nav sidebar to make them outlined

### PR DESCRIPTION
**Pull request by debsmita1**
## Description

- Outlined the nav sidebar icons
- updated some of the icons as per [Figma](https://www.figma.com/file/6ORS1mhUaxeyTBjMmE95Rn/Home-page-redesign?type=design&node-id=0-1&mode=design&t=hqJzxgFD3d3S83S5-0)

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-1423

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## Screenshot

Screenshot 2024-03-16 at 12 12 03 AM

### CODE REVIEW

**Comment by ShiranHi** [comment]
@debsmita1 looks good to me, thank you!

**Review by gashcrumb — APPROVED** [review]

**Pull request merged**
