### PR TITLE
RHIDP-4133: fix(homepage): fix some sonarcloud issues

### PR DESCRIPTION
**Pull request by jerolimov**
## Description

1. Fix 3 tiny sonarcloud issues:

   image

   image

   image

2. Improved example in (unused) plugins/dynamic-home-page/app-config.janus-idp.yaml

3. Marked properties in `useHomePageMountPoints.ts` as optional, also if its used optional chaining there already.

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

* #1532 should still work

/cc @ciiay @invincibleJai

### CODE REVIEW

**Comment by jerolimov** [comment]
> The image is available at: `quay.io/janus-idp/backstage-showcase:pr-1668`!

I tested this image on an OpenShift cluster and could still configure the sidebar and home page successfully:

image

```yaml
...
upstream:
  backstage:
    appConfig:
      # ..
      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.learning-path:
                parent: default.list
              default.list:
                icon: bookmarks
                title: References
              default.my-group:
                parent: default.list
          janus-idp.backstage-plugin-dynamic-home-page:
            mountPoints:
              - config:
                  layouts:
                    lg:
                      h: 1
                      w: 12
                    md:
                      h: 1
                      w: 12
                    sm:
                      h: 1
                      w: 12
                    xl:
                      h: 1
                      w: 12
                    xs:
                      h: 1
                      w: 12
                    xxs:
                      h: 1
                      w: 12
                  props:
                    align: center
                    title: Markdown examples
                importName: Headline
                mountPoint: home.page/cards
              - config:
                  layouts:
                    lg:
                      h: 4
                      w: 6
                    md:
                      h: 4
                      w: 6
                    sm:
                      h: 4
                      w: 6
                    xl:
                      h: 4
                      w: 6
                    xs:
                      h: 4
                      w: 6
                    xxs:
                      h: 4
                      w: 6
                  props:
                    content: >
                      ### RHDH


                      * [Website](https://developers.redhat.com/rhdh/overview)

                      *
                      [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)

                      * [GitHub
                      Showcase](https://github.com/janus-idp/backstage-showcase)

                      * [GitHub
                      Plugins](https://github.com/janus-idp/backstage-plugins)
                    title: Company links
                importName: MarkdownCard
                mountPoint: home.page/cards
              - config:
                  layouts:
                    lg:
                      h: 4
                      w: 6
                      x: 6
                    md:
                      h: 4
                      w: 6
                      x: 6
                    sm:
                      h: 4
                      w: 6
                      x: 6
                    xl:
                      h: 4
                      w: 6
                      x: 6
                    xs:
                      h: 4
                      w: 6
                      x: 6
                    xxs:
                      h: 4
                      w: 6
                      x: 6
                  props:
                    content: >
                      ### RHDH


                      * [Website](https://developers.redhat.com/rhdh/overview)

                      *
                      [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)

                      * [GitHub
                      Showcase](https://github.com/janus-idp/backstage-showcase)

                      * [GitHub
                      Plugins](https://github.com/janus-idp/backstage-plugins)
                    title: Important company links
                importName: Markdown
                mountPoint: home.page/cards
....
```

**Review by ciiay — APPROVED** [review]
Verified on OCP v4.15 cluster. Working as expected. 
image
image

/lgtm

**Pull request merged**
