### PR TITLE
fix(ui): RHIDP-2044 enable frontend plugin loading

### PR DESCRIPTION
**Pull request by gashcrumb**
## Description

This change removes the authentication requirement for the scalprum backend as it's used to serve static javascript content and related manifests.  This commit also adds identity support to the dynamic plugins info list frontend and migrates the backend to use the httpAuth service.

This change adds the new upstream guest authentication provider to the backend.  This provider is enabled by adding a "guest" entry to the `auth.providers` map.  This change also removes the dynamic-plugins-info-backend e2e test, as
it relies on an unauthenticated endpoint that isn't available anymore.  This functionaly is already covered by the UI e2e test and the component's unit test.

## Which issue(s) does this PR fix

- Fixes [RHIDP-2044](https://issues.redhat.com/browse/RHIDP-2044)
- Fixes [RHIDP-2043](https://issues.redhat.com/browse/RHIDP-2043)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer
This PR also adds the new upstream guest authentication provider.  You should be able to log into the app using this provider (or github/keycloak etc), click on the Administration tab and see the list of available plugins as a regular user.  There should be no HTTP 401 errors logged to the browser console when accessing the scalprum backend.  To use the guest authentication provider it now must be explicitly enabled in the auth provider map like so:

```yaml
# When running locally with "yarn start" only this is needed
auth:
  providers:
    guest: {}

# When running against a built image:
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
```

### CODE REVIEW

**Review by davidfestal — APPROVED** [review]

**Comment by gashcrumb** [comment]
Looks like fixing the tests could require fixing [RHIDP-2043](https://issues.redhat.com/browse/RHIDP-2043) as well, or the test must be adjusted to use a proper login and not the guest login.

**Comment by gashcrumb** [comment]
Looking into the test failure, had success running locally Friday but figured I couldn't be so lucky as to have the tests pass first try :smile:

**Comment by gashcrumb** [comment]
Think this quay e2e test is failing due to a different issue, @gustavolira is there an issue for fixing this test?:

image

**Comment by cmoulliard** [comment]
I deployed the image build from this PR on our OCP cluster where RHDP has been deployed using the Helm chart and pod is crashing as it cannot read an id

```
Loading config from MergedConfigSource{FileConfigSource{path="/opt/app-root/src/app-config.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config.example.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config.example.production.yaml"}, FileConfigSource{path="/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config-rhdh.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config-from-configmap.yaml"}, EnvConfigSource{count=1}}
(node:1) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
skipping '/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml' since it is not a directory
failed to load dynamic plugin manifest from '/opt/app-root/src/dynamic-plugins-root/lost+found' [Error: ENOENT: no such file or directory, open '/opt/app-root/src/dynamic-plugins-root/lost+found/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/app-root/src/dynamic-plugins-root/lost+found/package.json'
}
[2m2024-05-07T08:49:55.016Z[22m [34mbackstage[39m [32minfo[39m Found 6 new secrets in config that will be redacted 
[2m2024-05-07T08:49:55.020Z[22m [34mbackstage[39m [32minfo[39m skipping '/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml' since it is not a directory 
[2m2024-05-07T08:49:55.025Z[22m [34mbackstage[39m [31merror[39m failed to load dynamic plugin manifest from '/opt/app-root/src/dynamic-plugins-root/lost+found' ENOENT: no such file or directory, open '/opt/app-root/src/dynamic-plugins-root/lost+found/package.json' [36merrno[39m=-2 [36mcode[39m=ENOENT [36msyscall[39m=open [36mpath[39m=/opt/app-root/src/dynamic-plugins-root/lost+found/package.json [36mstack[39m=Error: ENOENT: no such file or directory, open '/opt/app-root/src/dynamic-plugins-root/lost+found/package.json'
[2m2024-05-07T08:49:55.923Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-kubernetes-backend-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-kubernetes-backend-dynamic-0.16.4' 
[2m2024-05-07T08:49:56.048Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-azure-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-azure-dynamic-0.1.8' 
[2m2024-05-07T08:49:56.102Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic-0.1.6' 
[2m2024-05-07T08:49:56.126Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic-0.1.6' 
[2m2024-05-07T08:49:56.167Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-gerrit-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-gerrit-dynamic-0.1.8' 
[2m2024-05-07T08:49:56.300Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-github-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-github-dynamic-0.2.6' 
[2m2024-05-07T08:49:56.430Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-gitlab-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-gitlab-dynamic-0.3.2' 
[2m2024-05-07T08:49:57.050Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-techdocs-backend-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-techdocs-backend-dynamic-1.10.3' 
[2m2024-05-07T08:49:57.052Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin '@janus-idp/backstage-scaffolder-backend-module-quay-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-quay-dynamic-1.3.10/alpha' 
[2m2024-05-07T08:49:57.094Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin '@janus-idp/backstage-scaffolder-backend-module-regex-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-regex-dynamic-1.3.10/alpha' 
[2m2024-05-07T08:49:57.173Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin '@qshift/plugin-quarkus-backend-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/qshift-plugin-quarkus-backend-dynamic-0.1.28/alpha' 
[2m2024-05-07T08:49:57.260Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'roadiehq-backstage-plugin-argo-cd-backend-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-backstage-plugin-argo-cd-backend-dynamic-3.0.0' 
[2m2024-05-07T08:49:57.342Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'roadiehq-scaffolder-backend-argocd-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic-1.1.25' 
[2m2024-05-07T08:49:57.353Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'roadiehq-scaffolder-backend-module-http-request-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-module-http-request-dynamic-4.1.10' 
[2m2024-05-07T08:49:57.442Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'roadiehq-scaffolder-backend-module-utils-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-module-utils-dynamic-1.14.1' 
[2m2024-05-07T08:49:57.457Z[22m [34mrootHttpRouter[39m [32minfo[39m Listening on :7007 
[2m2024-05-07T08:49:57.483Z[22m [34mauth[39m [32minfo[39m Enabled Provider Factories : {} 
[2m2024-05-07T08:49:57.507Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin 'backstage-plugin-kubernetes' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-kubernetes-0.11.8'  
[2m2024-05-07T08:49:57.507Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin 'backstage-plugin-techdocs' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-techdocs-1.10.3'  
[2m2024-05-07T08:49:57.507Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin '@janus-idp/backstage-plugin-rbac' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-plugin-rbac-1.17.4'  
[2m2024-05-07T08:49:57.507Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin '@janus-idp/backstage-plugin-tekton' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-plugin-tekton-3.5.18'  
[2m2024-05-07T08:49:57.507Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin '@janus-idp/backstage-plugin-topology' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-plugin-topology-1.18.14'  
[2m2024-05-07T08:49:57.508Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin '@qshift/plugin-quarkus' from 'file:///opt/app-root/src/dynamic-plugins-root/qshift-plugin-quarkus-0.1.28'  
[2m2024-05-07T08:49:57.508Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin '@qshift/plugin-quarkus-console' from 'file:///opt/app-root/src/dynamic-plugins-root/qshift-plugin-quarkus-console-0.1.28'  
[2m2024-05-07T08:49:57.508Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin 'roadiehq-backstage-plugin-argo-cd' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-backstage-plugin-argo-cd-2.6.4'  
[2m2024-05-07T08:49:57.512Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy created: /quay/api  -> https://quay.io/ 
[2m2024-05-07T08:49:57.512Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy rewrite rule created: "^/api/proxy/quay/api/?" ~> "/" 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /sonarqube due to Proxy target for route "/sonarqube" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jenkins/api due to Proxy target for route "/jenkins/api" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jira/api due to Proxy target for route "/jira/api" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /acr/api due to Proxy target for route "/acr/api" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jfrog-artifactory/api due to Proxy target for route "/jfrog-artifactory/api" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy created: /pagerduty  -> https://api.pagerduty.com 
[2m2024-05-07T08:49:57.513Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy rewrite rule created: "^/api/proxy/pagerduty/?" ~> "/" 
[2m2024-05-07T08:49:57.514Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /dynatrace due to Proxy target for route "/dynatrace" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.514Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /nexus-repository-manager due to Proxy target for route "/nexus-repository-manager" must be a string, but is of type undefined 
[2m2024-05-07T08:49:57.545Z[22m [34mauth[39m [32minfo[39m Configuring "database" as KeyStore provider 
[2m2024-05-07T08:49:57.551Z[22m [34mscaffolder[39m [32minfo[39m Starting scaffolder with the following actions enabled quay:create-repository, regex:replace, quarkus:app:create, quarkus:quickstart:clone, publish:azure, publish:bitbucketCloud, bitbucket:pipelines:run, publish:bitbucketServer, publish:bitbucketServer:pull-request, publish:gerrit, publish:gerrit:review, github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, gitlab:group:ensureExists, gitlab:issues:create, gitlab:projectAccessToken:create, gitlab:projectDeployToken:create, gitlab:projectVariable:create, gitlab:repo:push, publish:gitlab, publish:gitlab:merge-request, http:backstage:request, roadiehq:utils:zip, roadiehq:utils:sleep, roadiehq:utils:fs:write, roadiehq:utils:fs:append, roadiehq:utils:json:merge, roadiehq:utils:merge, roadiehq:utils:fs:parse, roadiehq:utils:fs:replace, roadiehq:utils:serialize:yaml, roadiehq:utils:serialize:json, roadiehq:utils:jsonata, roadiehq:utils:jsonata:yaml:transform, roadiehq:utils:jsonata:json:transform, argocd:create-resources, fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1768
            provides: Array.from(moduleInit.consumes).map((c) => c.id)
                                                                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1768:68
    at Array.map (<anonymous>)
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1768:55
    at Array.map (<anonymous>)
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1762:31
    at Array.map (<anonymous>)
    at BackendInitializer.doStart_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1758:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
    at async BackstageBackend.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1881:5)

Node.js v18.18.2
```

**Comment by gashcrumb** [comment]
@cmoulliard This PR doesn't change the backend loading really so I don't see how this would have been introduced by this particular code change.  Keep in mind that there's also been a few other changes merged in the past couple days as well along with dependency updates.  I think probably the first step in troubleshooting this issue would be to start disabling external plugins first and see if the backend loads or not with only the provided plugins.  Please open an issue if this problem persists.

**Pull request merged**
