### PR TITLE
chore(release): update rbac-backend to v5.2.1

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
## Description

update rbac-backend to v5.2.1

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-4732

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by dzemanov** [comment]
Works correctly!

**Comment by AndrienkoAleksandr** [comment]
Rebased to get e2e tests improvements from the main branch.

**Comment by AndrienkoAleksandr** [comment]
Close on favour: https://github.com/janus-idp/backstage-showcase/pull/1869

**Pull request closed without merging**
