### PR TITLE
chore(release): update keycloak-backend for RHDH 1.3.1

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
## Description

Update keycloak-backend for RHDH 1.3.1

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-3785
- Fixes https://issues.redhat.com/browse/RHIDP-4391

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by dzemanov** [comment]
Works as expected! 🎉

**Comment by christoph-jerolimov** [comment]
The image was broken, @ciiay fixed an issue with #1847, let see if this helps

/retest

**Pull request merged**
