### PR TITLE
fix(app): proxy for home and learning paths

### PR DESCRIPTION
**Pull request by invincibleJai**
## Description

This PR updated the credentials to be passed for the proxy

See Backstage 1.28 release notes about the BREAKING: Proxy backend plugin protected by default -
https://github.com/backstage/backstage/releases/tag/v1.28.0 

## Which issue(s) does this PR fix

- Fixes https://issues.redhat.com/browse/RHIDP-4015 

## How to test changes / Special notes to the reviewer

1. Setup custom data for home page , follow https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_developer_hub/proc-customize-rhdh-homepage_rhdh-getting-started#proc-customize-rhdh-homepage_rhdh-getting-started 
2. Setup costom data for learning path, follow https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_developer_hub/proc-customize-rhdh-learning-paths_rhdh-getting-started 

- Using JSON files that are hosted or GitHub or GitLab. To access the data from the JSON files, add below to app-config.yaml

```
proxy:
  endpoints:
    '/developer-hub':
      target: https://raw.githubusercontent.com/
      pathRewrite:
        '^/api/proxy/developer-hub/learning-paths': '/janus-idp/backstage-showcase/main/packages/app/public/learning-paths/data.json'
        '^/api/proxy/developer-hub': '/janus-idp/backstage-showcase/main/packages/app/public/homepage/data.json'
      changeOrigin: true
      secure: true
```

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by ciiay — APPROVED** [review]
Verified the PR image on OCP v4.15 and it works as expected. See the screen shots attached.
image
image

**Comment by jerolimov** [comment]
We should merge this in now to get this also in 1.3 by tomorrow. I like to get this merged also to rebase #1532 on that change.

/override ci/prow/e2e-tests

**Comment by jerolimov** [comment]
We should merge this now to get this also in 1.3 by today. I like to get this merged also to rebase #1532 on that change.

/override ci/prow/e2e-tests

**Pull request merged**
