### PR TITLE
chore: patch useRedisSets config for cache fix

### PR DESCRIPTION
**Pull request by JessicaJHee**
## Description

Adds patches for [this upstream fix](https://github.com/backstage/backstage/pull/26672) to use the `useRedisSets` config
* tested locally after adding the patch and confirmed that the `useRedisSets` config applies as expected

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Comment by kim-tsao** [comment]
Manually tested on the DAST instance with a clean install of the PR image

1.  Verified the patch is installed on the RHDH pod

```
sh-5.1$ cd patches
sh-5.1$ ls
@backstage+backend-defaults+0.4.1.patch                                @backstage+plugin-catalog-backend+1.24.0.patch
```

2.  Tested with `useRedisSets: false` and the verified the keys are in the expected format:

```
redb:10195> KEYS *
1) "sets:namespace:techdocs:techdocs:ZGVmYXVsdC9jb21wb25lbnQvYmFja3N0YWdlLXNob3djYXNlL2luZGV4Lmh0bWw="
2) "sets:namespace:techdocs:techdocs:ZGVmYXVsdC9jb21wb25lbnQvYmFja3N0YWdlLXNob3djYXNlL3NlYXJjaC9zZWFyY2hfaW5kZXguanNvbg=="
3) "sets:namespace:techdocs:techdocs:ZGVmYXVsdC9jb21wb25lbnQvYmFja3N0YWdlLXNob3djYXNlL2Fzc2V0cy9zdHlsZXNoZWV0cy9tYWluLjY1NDNhOTM1Lm1pbi5jc3M="
```

3.  Tested with `useRedisSets:true` and verified the keys are in the expected format:

```
redb:10195> KEYS *
1) "techdocs:D50ujQnjyWz9xLkSXo/VZoriCjGSxSq4o3PRFfGob8Q="
2) "techdocs:ZGVmYXVsdC9jb21wb25lbnQvYmFja3N0YWdlLXNob3djYXNlL3NlYXJjaC9zZWFyY2hfaW5kZXguanNvbg=="
3) "namespace:techdocs"
4) "techdocs:fHXC5tjcQf28DOgphEO46Ctm8+UB7tGZvi7TI4SugtQ="
```

**Comment by JessicaJHee** [comment]
For records: Locally tested as well with the options `useRedisSets=true` and `useRedisSets=false` and observed the expected change in cache key names 

With`useRedisSets=false` : 
image
With `useRedisSets=true` : 
image

**Pull request merged**
