### PR TITLE
chore(deps): update bulk import plugins

### PR DESCRIPTION
**Pull request by PatAKnight**
## Description

Updates the bulk import plugin.

## Which issue(s) does this PR fix

- Fixes [RHIDP-3931](https://issues.redhat.com/browse/RHIDP-3931)
- Fixes [RHIDP-4144](https://issues.redhat.com/browse/RHIDP-4144)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by nickboldt — COMMENTED** [review]
seems legit

/approve

**Comment by its-mitesh-kumar** [comment]
@PatAKnight ! Are you fixing e2e or should I pick it ?

**Comment by PatAKnight** [comment]
@its-mitesh-kumar, I was giving it a try but it looks like the RBAC plugin update is also blocked for roughly the same reason. So, I would appreciate some help!

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by debsmita1** [comment]
tested this on a cluster, and it works fine
/lgtm
Screenshot 2024-11-28 at 5 38 47 PM
Screenshot 2024-11-28 at 5 38 53 PM

**Comment by christoph-jerolimov** [comment]
Just rebased, re-add lgtm. :shipit: 

/lgtm

**Pull request merged**
