### PR TITLE
chore(e2e): rhdh deployment on openshift dedicated (osd) on gcp using helm chart

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Description

1. Added OSD cluster management scripts (create-osd.sh, destroy-osd.sh)
2. Updated test infrastructure to use OSD GCP cluster
3. Added Documentation.

## Which issue(s) does this PR fix

[RHIDP-4023](https://issues.redhat.com/browse/RHIDP-4023)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

### CODE REVIEW

**Review by zdrapela — COMMENTED** [review]
Hi @subhashkhileri, the nightly job for OSD will be set-up after we resolve the issue with GitHub login? Or what's the plan? :-) 
Otherwise it is looking great.

**Review by gustavolira — APPROVED** [review]

**Pull request merged**
